const IconsData = [
  {
    id: "html",
    name: "HTML",
    path: "public/html.svg",
    categories: ["web", "frontend"],
    keywords: ["html", "html5", "markup", "language"],
  },
  {
    id: "canva",
    name: "Canva",
    path: "public/canva.svg",
    categories: ["web", "design"],
    keywords: ["canva", "graphic", "design"],
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    path: "public/chatgpt.svg",
    categories: ["ai", "technology"],
    keywords: ["chatgpt", "openai", "chatbot"],
  },
  {
    id: "css",
    name: "CSS",
    path: "public/css.svg",
    categories: ["web", "frontend"],
    keywords: ["css", "stylesheets", "design"],
  },
  {
    id: "discord",
    name: "Discord",
    path: "public/discord.svg",
    categories: ["communication", "social"],
    keywords: ["discord", "chat", "gaming"],
  },
  {
    id: "figma",
    name: "Figma",
    path: "public/figma.svg",
    categories: ["design", "ui/ux"],
    keywords: ["figma", "design", "prototyping"],
  },
  {
    id: "firebase",
    name: "Firebase",
    path: "public/firebase.svg",
    categories: ["web", "backend"],
    keywords: ["firebase", "database", "backend"],
  },
  {
    id: "git",
    name: "Git",
    path: "public/git.svg",
    categories: ["development", "version control"],
    keywords: ["git", "version control", "code"],
  },
  {
    id: "github",
    name: "GitHub",
    path: "public/github.svg",
    categories: ["development", "version control"],
    keywords: ["github", "git", "repository"],
  },
  {
    id: "gmail",
    name: "Gmail",
    path: "public/gmail.svg",
    categories: ["communication", "email"],
    keywords: ["gmail", "email", "google"],
  },
  {
    id: "instagram",
    name: "Instagram",
    path: "public/instagram.svg",
    categories: ["social", "media"],
    keywords: ["instagram", "social media", "photos"],
  },
  {
    id: "javascript",
    name: "JavaScript",
    path: "public/javascript.svg",
    categories: ["web", "programming"],
    keywords: ["javascript", "programming", "language"],
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    path: "public/linkedin.svg",
    categories: ["social", "professional"],
    keywords: ["linkedin", "professional", "networking"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    path: "public/mongodb.svg",
    categories: ["database", "backend"],
    keywords: ["mongodb", "database", "nosql"],
  },
  {
    id: "nextjs",
    name: "Next.js",
    path: "public/nextjs.svg",
    categories: ["web", "framework"],
    keywords: ["nextjs", "react", "javascript"],
  },
  {
    id: "notion",
    name: "Notion",
    path: "public/notion.svg",
    categories: ["productivity", "tool"],
    keywords: ["notion", "organization", "notes"],
  },
  {
    id: "openai",
    name: "OpenAI",
    path: "public/openai.svg",
    categories: ["ai", "technology"],
    keywords: ["openai", "artificial intelligence", "research"],
  },
  {
    id: "postman",
    name: "Postman",
    path: "public/postman.svg",
    categories: ["development", "tool"],
    keywords: ["postman", "api", "testing"],
  },
  {
    id: "react-native",
    name: "React Native",
    path: "public/react-native.svg",
    categories: ["mobile", "framework"],
    keywords: ["react native", "mobile app", "javascript"],
  },
  {
    id: "react",
    name: "React",
    path: "public/react.svg",
    categories: ["web", "library"],
    keywords: ["react", "javascript", "ui"],
  },
  {
    id: "redux",
    name: "Redux",
    path: "public/redux.svg",
    categories: ["web", "state-management"],
    keywords: ["redux", "javascript", "state"],
  },
  {
    id: "sass",
    name: "SASS",
    path: "public/sass.svg",
    categories: ["web", "frontend"],
    keywords: ["sass", "css", "style"],
  },
  {
    id: "tailwindcss",
    name: "Tailwind CSS",
    path: "public/tailwindcss.svg",
    categories: ["web", "frontend"],
    keywords: ["tailwindcss", "css", "design"],
  },
  {
    id: "typescript",
    name: "TypeScript",
    path: "public/typescript.svg",
    categories: ["web", "programming"],
    keywords: ["typescript", "javascript", "language"],
  },
  {
    id: "vite",
    name: "Vite",
    path: "public/vite.svg",
    categories: ["web", "tool"],
    keywords: ["vite", "build tool", "javascript"],
  },
  {
    id: "vscode",
    name: "VS Code",
    path: "public/vscode.svg",
    categories: ["development", "tool"],
    keywords: ["vscode", "editor", "code"],
  },
  {
    id: "wordpress",
    name: "WordPress",
    path: "public/wordpress.svg",
    categories: ["web", "cms"],
    keywords: ["wordpress", "cms", "blogging"],
  },
];

export default IconsData;
