export const categoriesData = [
  "Languages",
  "Frontend",
  "Backend",
  "Database",
  "Design",
  "Native App",
  "DevOps & AI/ML",
  "Productivity",
  "Media",
  "Companies",
  "Others",
] as const;

export const iconsData: IconDataType[] = [
  {
    id: "apache",
    name: "Apache",
    path: "icons/apache.svg",
    categories: ["Backend"],
    keywords: ["apache", "server", "web"],
  },
  {
    id: "appwrite",
    name: "Appwrite",
    path: "icons/appwrite.svg",
    categories: ["Backend", "Database"],
    keywords: ["appwrite", "backend", "database"],
  },
  {
    id: "arc",
    name: "ARC",
    path: "icons/arc.svg",
    categories: ["Others"],
    keywords: ["arc", "web", "development"],
  },
  {
    id: "astro",
    name: "Astro",
    path: "icons/astro.svg",
    categories: ["Frontend"],
    keywords: ["astro", "frontend", "framework"],
  },
  {
    id: "atlassian",
    name: "Atlassian",
    path: "icons/atlassian.svg",
    categories: ["Productivity"],
    keywords: ["atlassian", "tools", "collaboration"],
  },
  {
    id: "atom",
    name: "Atom",
    path: "icons/atom.svg",
    categories: ["Productivity"],
    keywords: ["atom", "editor", "code"],
  },
  {
    id: "auth0",
    name: "Auth0",
    path: "icons/auth0.svg",
    categories: ["Backend"],
    keywords: ["auth0", "authentication", "security"],
  },
  {
    id: "avajs",
    name: "AVA",
    path: "icons/avajs.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["avajs", "testing", "javascript"],
  },
  {
    id: "aws",
    name: "AWS",
    path: "icons/aws.svg",
    categories: ["Backend", "DevOps & AI/ML"],
    keywords: ["aws", "cloud", "amazon"],
  },
  {
    id: "axiom",
    name: "Axiom",
    path: "icons/axiom.svg",
    categories: ["Others"],
    keywords: ["axiom", "data", "analysis"],
  },
  {
    id: "axm",
    name: "AXM",
    path: "icons/axm.svg",
    categories: ["Others"],
    keywords: ["axm"],
  },
  {
    id: "axure",
    name: "Axure",
    path: "icons/axure.svg",
    categories: ["Design"],
    keywords: ["axure", "design", "prototyping"],
  },
  {
    id: "azure",
    name: "Azure",
    path: "icons/azure.svg",
    categories: ["Backend", "DevOps & AI/ML"],
    keywords: ["azure", "microsoft", "cloud"],
  },
  {
    id: "babel",
    name: "Babel",
    path: "icons/babel.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["babel", "javascript", "compiler"],
  },
  {
    id: "backbonejs",
    name: "Backbone.js",
    path: "icons/backbonejs.svg",
    categories: ["Frontend"],
    keywords: ["backbonejs", "frontend", "framework"],
  },
  {
    id: "bash",
    name: "Bash",
    path: "icons/bash.svg",
    categories: ["Others"],
    keywords: ["bash", "shell", "scripting"],
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    path: "icons/bitbucket.svg",
    categories: ["Productivity"],
    keywords: ["bitbucket", "git", "version control"],
  },
  {
    id: "bitnami",
    name: "Bitnami",
    path: "icons/bitnami.svg",
    categories: ["Backend", "DevOps & AI/ML"],
    keywords: ["bitnami", "cloud", "stacks"],
  },
  {
    id: "blueprintjs",
    name: "Blueprint.js",
    path: "icons/blueprintjs.svg",
    categories: ["Frontend"],
    keywords: ["blueprintjs", "ui", "react"],
  },
  {
    id: "bootstrap4",
    name: "Bootstrap 4",
    path: "icons/bootstrap4.svg",
    categories: ["Frontend", "Design"],
    keywords: ["bootstrap4", "css", "frontend"],
  },
  {
    id: "bootstrap5",
    name: "Bootstrap 5",
    path: "icons/bootstrap5.svg",
    categories: ["Frontend", "Design"],
    keywords: ["bootstrap5", "css", "frontend"],
  },
  // {
  //   id: "brave",
  //   name: "Brave",
  //   path: "icons/brave.svg",
  //   categories: ["Others"],
  //   keywords: ["brave", "browser", "privacy"],
  // },
  {
    id: "bulmaui",
    name: "Bulma UI",
    path: "icons/bulmaui.svg",
    categories: ["Frontend", "Design"],
    keywords: ["bulmaui", "css", "frontend"],
  },
  {
    id: "bunjs",
    name: "Bun.js",
    path: "icons/bunjs.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["bunjs", "javascript", "runtime"],
  },
  {
    id: "c-sharp",
    name: "C#",
    path: "icons/c-sharp.svg",
    categories: ["Languages"],
    keywords: ["c-sharp", "programming", "microsoft", "c#"],
  },
  {
    id: "c-plus-plus",
    name: "C++",
    path: "icons/c-plus-plus.svg",
    categories: ["Languages"],
    keywords: ["c++", "programming", "performance"],
  },
  {
    id: "cakephp",
    name: "CakePHP",
    path: "icons/cakephp.svg",
    categories: ["Backend"],
    keywords: ["cakephp", "php", "framework"],
  },
  {
    id: "canva",
    name: "Canva",
    path: "icons/canva.svg",
    categories: ["Design"],
    keywords: ["canva", "design", "graphics"],
  },
  {
    id: "cassandradb",
    name: "Cassandra DB",
    path: "icons/cassandradb.svg",
    categories: ["Database"],
    keywords: ["cassandradb", "database", "nosql"],
  },
  {
    id: "chakraui",
    name: "Chakra UI",
    path: "icons/chakraui.svg",
    categories: ["Frontend", "Design"],
    keywords: ["chakraui", "ui", "react"],
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    path: "icons/chatgpt.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["chatgpt", "ai", "openai"],
  },
  {
    id: "chrome",
    name: "Chrome",
    path: "icons/chrome.svg",
    categories: ["Others"],
    keywords: ["chrome", "browser", "google"],
  },
  {
    id: "chromium",
    name: "Chromium",
    path: "icons/chromium.svg",
    categories: ["Others"],
    keywords: ["chromium", "browser", "opensource"],
  },
  {
    id: "circleci",
    name: "CircleCI",
    path: "icons/circleci.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["circleci", "ci", "cd"],
  },
  {
    id: "clickhouse",
    name: "ClickHouse",
    path: "icons/clickhouse.svg",
    categories: ["Database"],
    keywords: ["clickhouse", "database", "analytics"],
  },
  {
    id: "clojure",
    name: "Clojure",
    path: "icons/clojure.svg",
    categories: ["Languages"],
    keywords: ["clojure", "functional", "jvm"],
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    path: "icons/cloudflare.svg",
    categories: ["Others"],
    keywords: ["cloudflare", "security", "cdn"],
  },
  {
    id: "cloudinary",
    name: "Cloudinary",
    path: "icons/cloudinary.svg",
    categories: ["Media"],
    keywords: ["cloudinary", "media", "cloud"],
  },
  {
    id: "codefresh",
    name: "Codefresh",
    path: "icons/codefresh.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["codefresh", "ci", "cd"],
  },
  {
    id: "codeigniter",
    name: "CodeIgniter",
    path: "icons/codeigniter.svg",
    categories: ["Backend"],
    keywords: ["codeigniter", "php", "framework"],
  },
  {
    id: "copilot",
    name: "Copilot",
    path: "icons/copilot.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["copilot", "ai", "coding"],
  },
  {
    id: "crystal",
    name: "Crystal",
    path: "icons/crystal.svg",
    categories: ["Languages"],
    keywords: ["crystal", "programming", "performance"],
  },
  {
    id: "css3",
    name: "CSS3",
    path: "icons/css3.svg",
    categories: ["Frontend", "Design"],
    keywords: ["css3", "design", "stylesheets"],
  },
  {
    id: "cypress",
    name: "Cypress",
    path: "icons/cypress.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["cypress", "testing", "javascript"],
  },
  {
    id: "dart",
    name: "Dart",
    path: "icons/dart.svg",
    categories: ["Languages"],
    keywords: ["dart", "programming", "app development"],
  },
  {
    id: "datadog",
    name: "Datadog",
    path: "icons/datadog.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["datadog", "monitoring", "analytics"],
  },
  {
    id: "deno",
    name: "Deno",
    path: "icons/deno.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["deno", "javascript", "typescript"],
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    path: "icons/digitalocean.svg",
    categories: ["Backend"],
    keywords: ["digitalocean", "cloud", "servers"],
  },
  {
    id: "discord",
    name: "Discord",
    path: "icons/discord.svg",
    categories: ["Productivity"],
    keywords: ["discord", "chat", "voice"],
  },
  {
    id: "django",
    name: "Django",
    path: "icons/django.svg",
    categories: ["Backend"],
    keywords: ["django", "python", "web"],
  },
  {
    id: "dlang",
    name: "D Language",
    path: "icons/dlang.svg",
    categories: ["Languages"],
    keywords: ["dlang", "programming", "performance"],
  },
  {
    id: "docker",
    name: "Docker",
    path: "icons/docker.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["docker", "containers", "devops"],
  },
  {
    id: "docusaurus",
    name: "Docusaurus",
    path: "icons/docusaurus.svg",
    categories: ["Others"],
    keywords: ["docusaurus", "documentation", "static site"],
  },
  {
    id: "dovetail",
    name: "Dovetail",
    path: "icons/dovetail.svg",
    categories: ["Design"],
    keywords: ["dovetail", "design", "prototyping"],
  },
  {
    id: "ec2",
    name: "EC2",
    path: "icons/ec2.svg",
    categories: ["Backend"],
    keywords: ["ec2", "aws", "cloud"],
  },
  {
    id: "edge",
    name: "Edge",
    path: "icons/edge.svg",
    categories: ["Others"],
    keywords: ["edge", "browser", "microsoft"],
  },
  {
    id: "elastic",
    name: "Elastic",
    path: "icons/elastic.svg",
    categories: ["Database"],
    keywords: ["elastic", "search", "elasticsearch"],
  },
  {
    id: "electron",
    name: "Electron",
    path: "icons/electron.svg",
    categories: ["Native App"],
    keywords: ["electron", "desktop", "apps"],
  },
  {
    id: "elementui",
    name: "Element UI",
    path: "icons/elementui.svg",
    categories: ["Frontend", "Design"],
    keywords: ["elementui", "ui", "vue"],
  },
  {
    id: "elixir",
    name: "Elixir",
    path: "icons/elixir.svg",
    categories: ["Languages"],
    keywords: ["elixir", "functional", "concurrent"],
  },
  {
    id: "ember",
    name: "Ember",
    path: "icons/ember.svg",
    categories: ["Frontend"],
    keywords: ["ember", "frontend", "framework"],
  },
  {
    id: "erlang",
    name: "Erlang",
    path: "icons/erlang.svg",
    categories: ["Languages"],
    keywords: ["erlang", "functional", "concurrent"],
  },
  {
    id: "esbuild",
    name: "esbuild",
    path: "icons/esbuild.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["esbuild", "javascript", "builder"],
  },
  {
    id: "eslint",
    name: "ESLint",
    path: "icons/eslint.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["eslint", "javascript", "linting"],
  },
  {
    id: "faunadb",
    name: "FaunaDB",
    path: "icons/faunadb.svg",
    categories: ["Database"],
    keywords: ["faunadb", "database", "nosql"],
  },
  {
    id: "figma",
    name: "Figma",
    path: "icons/figma.svg",
    categories: ["Design"],
    keywords: ["figma", "design", "ui"],
  },
  {
    id: "firebase",
    name: "Firebase",
    path: "icons/firebase.svg",
    categories: ["Backend", "Database"],
    keywords: ["firebase", "database", "google"],
  },
  {
    id: "firefox",
    name: "Firefox",
    path: "icons/firefox.svg",
    categories: ["Others"],
    keywords: ["firefox", "browser", "mozilla"],
  },
  {
    id: "flask",
    name: "Flask",
    path: "icons/flask.svg",
    categories: ["Backend"],
    keywords: ["flask", "python", "web"],
  },
  {
    id: "flutter",
    name: "Flutter",
    path: "icons/flutter.svg",
    categories: ["Native App"],
    keywords: ["flutter", "mobile", "apps"],
  },
  {
    id: "flyio",
    name: "Fly.io",
    path: "icons/flyio.svg",
    categories: ["Backend"],
    keywords: ["flyio", "hosting", "cloud"],
  },
  {
    id: "framer",
    name: "Framer",
    path: "icons/framer.svg",
    categories: ["Design"],
    keywords: ["framer", "design", "prototyping"],
  },
  {
    id: "gatsby",
    name: "Gatsby",
    path: "icons/gatsby.svg",
    categories: ["Frontend"],
    keywords: ["gatsby", "react", "static site"],
  },
  {
    id: "git",
    name: "Git",
    path: "icons/git.svg",
    categories: ["Productivity"],
    keywords: ["git", "version control", "code"],
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    path: "icons/github-copilot.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["github-copilot", "ai", "coding"],
  },
  {
    id: "github",
    name: "GitHub",
    path: "icons/github.svg",
    categories: ["Productivity"],
    keywords: ["github", "git", "repository"],
  },
  {
    id: "gitlab",
    name: "GitLab",
    path: "icons/gitlab.svg",
    categories: ["Productivity"],
    keywords: ["gitlab", "git", "ci/cd"],
  },
  {
    id: "gmail",
    name: "Gmail",
    path: "icons/gmail.svg",
    categories: ["Productivity"],
    keywords: ["gmail", "email", "google"],
  },
  {
    id: "go",
    name: "Go",
    path: "icons/go.svg",
    categories: ["Languages"],
    keywords: ["go", "programming", "google"],
  },
  {
    id: "google-cloud",
    name: "Google Cloud",
    path: "icons/google-cloud.svg",
    categories: ["Backend", "DevOps & AI/ML"],
    keywords: ["google-cloud", "cloud", "google"],
  },
  {
    id: "grafana",
    name: "Grafana",
    path: "icons/grafana.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["grafana", "monitoring", "metrics"],
  },
  {
    id: "grafbase",
    name: "Grafbase",
    path: "icons/grafbase.svg",
    categories: ["Database"],
    keywords: ["grafbase", "graphql", "database"],
  },
  {
    id: "graphite",
    name: "Graphite",
    path: "icons/graphite.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["graphite", "monitoring", "metrics"],
  },
  {
    id: "graphql",
    name: "GraphQL",
    path: "icons/graphql.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["graphql", "api", "query"],
  },
  {
    id: "gridsome",
    name: "Gridsome",
    path: "icons/gridsome.svg",
    categories: ["Frontend"],
    keywords: ["gridsome", "vue", "static site"],
  },
  {
    id: "gruntjs",
    name: "Grunt.js",
    path: "icons/gruntjs.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["gruntjs", "javascript", "task"],
  },
  {
    id: "gulp",
    name: "Gulp",
    path: "icons/gulp.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["gulp", "javascript", "task"],
  },
  {
    id: "haskell",
    name: "Haskell",
    path: "icons/haskell.svg",
    categories: ["Languages"],
    keywords: ["haskell", "functional", "programming"],
  },
  {
    id: "headlessui",
    name: "Headless UI",
    path: "icons/headlessui.svg",
    categories: ["Frontend", "Design"],
    keywords: ["headlessui", "ui", "tailwind"],
  },
  {
    id: "heroku",
    name: "Heroku",
    path: "icons/heroku.svg",
    categories: ["Backend"],
    keywords: ["heroku", "cloud", "hosting"],
  },
  {
    id: "hexo",
    name: "Hexo",
    path: "icons/hexo.svg",
    categories: ["Others"],
    keywords: ["hexo", "static site", "nodejs"],
  },
  {
    id: "hhvm",
    name: "HHVM",
    path: "icons/hhvm.svg",
    categories: ["Others"],
    keywords: ["hhvm", "virtual machine", "php"],
  },
  {
    id: "homebrew",
    name: "Homebrew",
    path: "icons/homebrew.svg",
    categories: ["Others"],
    keywords: ["homebrew", "macos", "linux"],
  },
  {
    id: "hotjar",
    name: "Hotjar",
    path: "icons/hotjar.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["hotjar", "analytics", "user behavior"],
  },
  {
    id: "html5",
    name: "HTML5",
    path: "icons/html5.svg",
    categories: ["Frontend", "Design"],
    keywords: ["html5", "markup", "web"],
  },
  // {
  //   id: "hyper",
  //   name: "Hyper",
  //   path: "icons/hyper.svg",
  //   categories: ["Productivity"],
  //   keywords: ["hyper", "terminal", "shell"],
  // },
  {
    id: "hyper2",
    name: "Hyper 2",
    path: "icons/hyper2.svg",
    categories: ["Productivity"],
    keywords: ["hyper2", "terminal", "shell"],
  },
  {
    id: "i18next",
    name: "i18next",
    path: "icons/i18next.svg",
    categories: ["Others"],
    keywords: ["i18next", "i18n", "localization"],
  },
  {
    id: "indesign",
    name: "InDesign",
    path: "icons/indesign.svg",
    categories: ["Design"],
    keywords: ["indesign", "adobe", "layout"],
  },
  // {
  //   id: "inkspace",
  //   name: "Inkspace",
  //   path: "icons/inkspace.svg",
  //   categories: ["Design"],
  //   keywords: ["inkspace", "vector", "graphics"],
  // },
  {
    id: "insomnia",
    name: "Insomnia",
    path: "icons/insomnia.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["insomnia", "api", "testing"],
  },
  {
    id: "instagram",
    name: "Instagram",
    path: "icons/instagram.svg",
    categories: ["Media"],
    keywords: ["instagram", "social", "media"],
  },
  {
    id: "internet-explorer",
    name: "Internet Explorer",
    path: "icons/internet-explorer.svg",
    categories: ["Others"],
    keywords: ["internet-explorer", "browser", "microsoft"],
  },
  {
    id: "invision",
    name: "InVision",
    path: "icons/invision.svg",
    categories: ["Design"],
    keywords: ["invision", "design", "prototyping"],
  },
  {
    id: "ionic",
    name: "Ionic",
    path: "icons/ionic.svg",
    categories: ["Native App"],
    keywords: ["ionic", "mobile", "hybrid"],
  },
  {
    id: "jamstack",
    name: "JAMstack",
    path: "icons/jamstack.svg",
    categories: ["Others"],
    keywords: ["jamstack", "static site", "web"],
  },
  {
    id: "java",
    name: "Java",
    path: "icons/java.svg",
    categories: ["Languages"],
    keywords: ["java", "programming", "jvm"],
  },
  {
    id: "javascript",
    name: "JavaScript",
    path: "icons/javascript.svg",
    categories: ["Languages"],
    keywords: ["javascript", "programming", "web"],
  },
  {
    id: "jest",
    name: "Jest",
    path: "icons/jest.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["jest", "testing", "javascript"],
  },
  {
    id: "jira",
    name: "Jira",
    path: "icons/jira.svg",
    categories: ["Productivity"],
    keywords: ["jira", "atlassian", "project management"],
  },
  {
    id: "jquery",
    name: "jQuery",
    path: "icons/jquery.svg",
    categories: ["Frontend"],
    keywords: ["jquery", "javascript", "library"],
  },
  {
    id: "jslint",
    name: "JSLint",
    path: "icons/jslint.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["jslint", "javascript", "linting"],
  },
  {
    id: "json",
    name: "JSON",
    path: "icons/json.svg",
    categories: ["Others"],
    keywords: ["json", "data", "format"],
  },
  {
    id: "kibana",
    name: "Kibana",
    path: "icons/kibana.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["kibana", "elasticsearch", "dashboard"],
  },
  {
    id: "kotlin",
    name: "Kotlin",
    path: "icons/kotlin.svg",
    categories: ["Languages"],
    keywords: ["kotlin", "programming", "jvm"],
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    path: "icons/kubernetes.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["kubernetes", "containers", "orchestration"],
  },
  {
    id: "laravel",
    name: "Laravel",
    path: "icons/laravel.svg",
    categories: ["Backend"],
    keywords: ["laravel", "php", "web"],
  },
  {
    id: "less",
    name: "Less",
    path: "icons/less.svg",
    categories: ["Frontend", "Design"],
    keywords: ["less", "css", "preprocessor"],
  },
  {
    id: "lightroom",
    name: "Lightroom",
    path: "icons/lightroom.svg",
    categories: ["Design"],
    keywords: ["lightroom", "adobe", "photo editing"],
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    path: "icons/linkedin.svg",
    categories: ["Media"],
    keywords: ["linkedin", "social", "network"],
  },
  {
    id: "linux",
    name: "Linux",
    path: "icons/linux.svg",
    categories: ["Others"],
    keywords: ["linux", "os", "open source"],
  },
  {
    id: "lit",
    name: "Lit",
    path: "icons/lit.svg",
    categories: ["Frontend"],
    keywords: ["lit", "web components", "javascript"],
  },
  {
    id: "liveblocks",
    name: "Liveblocks",
    path: "icons/liveblocks.svg",
    categories: ["Backend"],
    keywords: ["liveblocks", "real-time", "collaboration"],
  },
  {
    id: "logrocket",
    name: "LogRocket",
    path: "icons/logrocket.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["logrocket", "monitoring", "user experience"],
  },
  {
    id: "lokalise",
    name: "Lokalise",
    path: "icons/lokalise.svg",
    categories: ["Others"],
    keywords: ["lokalise", "localization", "translation"],
  },
  {
    id: "lua",
    name: "Lua",
    path: "icons/lua.svg",
    categories: ["Languages"],
    keywords: ["lua", "scripting", "game development"],
  },
  {
    id: "lunacy",
    name: "Lunacy",
    path: "icons/lunacy.svg",
    categories: ["Design"],
    keywords: ["lunacy", "design", "vector graphics"],
  },
  {
    id: "mariadb",
    name: "MariaDB",
    path: "icons/mariadb.svg",
    categories: ["Database"],
    keywords: ["mariadb", "database", "mysql"],
  },
  {
    id: "marionette",
    name: "Marionette",
    path: "icons/marionette.svg",
    categories: ["Frontend"],
    keywords: ["marionette", "javascript", "mvc"],
  },
  {
    id: "markdown",
    name: "Markdown",
    path: "icons/markdown.svg",
    categories: ["Others"],
    keywords: ["markdown", "writing", "documentation"],
  },
  {
    id: "materialui",
    name: "Material UI",
    path: "icons/materialui.svg",
    categories: ["Frontend", "Design"],
    keywords: ["materialui", "ui", "react"],
  },
  {
    id: "meta",
    name: "Meta",
    path: "icons/meta.svg",
    categories: ["Companies"],
    keywords: ["meta", "facebook", "social media"],
  },
  {
    id: "microsoft",
    name: "Microsoft",
    path: "icons/microsoft.svg",
    categories: ["Companies"],
    keywords: ["microsoft", "software", "technology"],
  },
  {
    id: "miro",
    name: "Miro",
    path: "icons/miro.svg",
    categories: ["Design"],
    keywords: ["miro", "whiteboard", "collaboration"],
  },
  {
    id: "mochajs",
    name: "MochaJS",
    path: "icons/mochajs.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["mochajs", "testing", "javascript"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    path: "icons/mongodb.svg",
    categories: ["Database"],
    keywords: ["mongodb", "database", "nosql"],
  },
  {
    id: "mozilla",
    name: "Mozilla",
    path: "icons/mozilla.svg",
    categories: ["Companies"],
    keywords: ["mozilla", "software", "technology"],
  },
  {
    id: "mysql",
    name: "MySQL",
    path: "icons/mysql.svg",
    categories: ["Database"],
    keywords: ["mysql", "database", "sql"],
  },
  {
    id: "neovim",
    name: "NeoVim",
    path: "icons/neovim.svg",
    categories: ["Productivity"],
    keywords: ["neovim", "editor", "vim"],
  },
  {
    id: "nestjs",
    name: "NestJS",
    path: "icons/nestjs.svg",
    categories: ["Backend"],
    keywords: ["nestjs", "nodejs", "typescript"],
  },
  {
    id: "netlify",
    name: "Netlify",
    path: "icons/netlify.svg",
    categories: ["Backend"],
    keywords: ["netlify", "hosting", "static site"],
  },
  {
    id: "netlify2",
    name: "Netlify 2",
    path: "icons/netlify2.svg",
    categories: ["Backend"],
    keywords: ["netlify2", "hosting", "static site"],
  },
  {
    id: "nextjs-wordmark",
    name: "Next.js Wordmark",
    path: "icons/nextjs-wordmark.svg",
    categories: ["Frontend"],
    keywords: ["nextjs-wordmark", "nextjs", "react"],
  },
  {
    id: "nextjs",
    name: "Next.js",
    path: "icons/nextjs.svg",
    categories: ["Frontend"],
    keywords: ["nextjs", "react", "ssr"],
  },
  {
    id: "nim",
    name: "Nim",
    path: "icons/nim.svg",
    categories: ["Languages"],
    keywords: ["nim", "programming", "efficient"],
  },
  // {
  //   id: "nitro",
  //   name: "Nitro",
  //   path: "icons/nitro.svg",
  //   categories: ["Others"],
  //   keywords: ["nitro", "development", "tools"],
  // },
  {
    id: "nodejs",
    name: "Node.js",
    path: "icons/nodejs.svg",
    categories: ["Backend"],
    keywords: ["nodejs", "javascript", "server"],
  },
  {
    id: "npm-wordmark",
    name: "NPM Wordmark",
    path: "icons/npm-wordmark.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["npm-wordmark", "npm", "javascript"],
  },
  {
    id: "npm",
    name: "NPM",
    path: "icons/npm.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["npm", "package manager", "nodejs"],
  },
  {
    id: "nuxtjs",
    name: "Nuxt.js",
    path: "icons/nuxtjs.svg",
    categories: ["Frontend"],
    keywords: ["nuxtjs", "vue", "ssr"],
  },
  {
    id: "ocaml",
    name: "OCaml",
    path: "icons/ocaml.svg",
    categories: ["Languages"],
    keywords: ["ocaml", "functional", "programming"],
  },
  {
    id: "onedrive",
    name: "OneDrive",
    path: "icons/onedrive.svg",
    categories: ["Others"],
    keywords: ["onedrive", "cloud", "microsoft"],
  },
  {
    id: "openai",
    name: "OpenAI",
    path: "icons/openai.svg",
    categories: ["Companies", "DevOps & AI/ML"],
    keywords: ["openai", "ai", "machine learning"],
  },
  {
    id: "opera",
    name: "Opera",
    path: "icons/opera.svg",
    categories: ["Others"],
    keywords: ["opera", "browser", "web"],
  },
  {
    id: "oracle",
    name: "Oracle",
    path: "icons/oracle.svg",
    categories: ["Companies", "Database"],
    keywords: ["oracle", "database", "enterprise"],
  },
  {
    id: "pandacss",
    name: "Panda CSS",
    path: "icons/pandacss.svg",
    categories: ["Frontend", "Design"],
    keywords: ["pandacss", "css", "styling"],
  },
  {
    id: "photoshop",
    name: "Photoshop",
    path: "icons/photoshop.svg",
    categories: ["Design"],
    keywords: ["photoshop", "adobe", "graphics"],
  },
  {
    id: "php",
    name: "PHP",
    path: "icons/php.svg",
    categories: ["Languages", "Backend"],
    keywords: ["php", "web", "backend"],
  },
  {
    id: "pinia",
    name: "Pinia",
    path: "icons/pinia.svg",
    categories: ["Frontend"],
    keywords: ["pinia", "state", "vue"],
  },
  {
    id: "pixijs",
    name: "PixiJS",
    path: "icons/pixijs.svg",
    categories: ["Media"],
    keywords: ["pixijs", "webgl", "rendering"],
  },
  {
    id: "playwright",
    name: "Playwright",
    path: "icons/playwright.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["playwright", "testing", "browser"],
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    path: "icons/postgresql.svg",
    categories: ["Database"],
    keywords: ["postgresql", "database", "sql"],
  },
  {
    id: "postman",
    name: "Postman",
    path: "icons/postman.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["postman", "api", "testing"],
  },
  {
    id: "powershell",
    name: "PowerShell",
    path: "icons/powershell.svg",
    categories: ["Others"],
    keywords: ["powershell", "shell", "scripting"],
  },
  {
    id: "preact",
    name: "Preact",
    path: "icons/preact.svg",
    categories: ["Frontend"],
    keywords: ["preact", "react", "performance"],
  },
  {
    id: "presto",
    name: "Presto",
    path: "icons/presto.svg",
    categories: ["Database"],
    keywords: ["presto", "sql", "analytics"],
  },
  {
    id: "prettier",
    name: "Prettier",
    path: "icons/prettier.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["prettier", "code", "formatter"],
  },
  {
    id: "prisma",
    name: "Prisma",
    path: "icons/prisma.svg",
    categories: ["Backend"],
    keywords: ["prisma", "orm", "database"],
  },
  {
    id: "pugjs",
    name: "Pug.js",
    path: "icons/pugjs.svg",
    categories: ["Backend"],
    keywords: ["pugjs", "template", "html"],
  },
  {
    id: "pwa",
    name: "PWA",
    path: "icons/pwa.svg",
    categories: ["Frontend"],
    keywords: ["pwa", "web app", "offline"],
  },
  {
    id: "python",
    name: "Python",
    path: "icons/python.svg",
    categories: ["Languages"],
    keywords: ["python", "programming", "general purpose"],
  },
  {
    id: "pytorch",
    name: "PyTorch",
    path: "icons/pytorch.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["pytorch", "machine learning", "deep learning"],
  },
  {
    id: "pytorch3d",
    name: "PyTorch3D",
    path: "icons/pytorch3d.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["pytorch3d", "3d", "machine learning"],
  },
  {
    id: "qwik",
    name: "Qwik",
    path: "icons/qwik.svg",
    categories: ["Frontend"],
    keywords: ["qwik", "frontend", "performance"],
  },
  {
    id: "radixui",
    name: "Radix UI",
    path: "icons/radixui.svg",
    categories: ["Frontend", "Design"],
    keywords: ["radixui", "ui", "design systems"],
  },
  {
    id: "rails",
    name: "Rails",
    path: "icons/rails.svg",
    categories: ["Backend"],
    keywords: ["rails", "ruby", "web"],
  },
  {
    id: "railway",
    name: "Railway",
    path: "icons/railway.svg",
    categories: ["Backend"],
    keywords: ["railway", "hosting", "cloud"],
  },
  {
    id: "react-query",
    name: "React Query",
    path: "icons/react-query.svg",
    categories: ["Frontend"],
    keywords: ["react-query", "react", "data fetching"],
  },
  {
    id: "reactjs",
    name: "React",
    path: "icons/reactjs.svg",
    categories: ["Frontend"],
    keywords: ["reactjs", "ui", "javascript"],
  },
  {
    id: "reactrouter",
    name: "React Router",
    path: "icons/reactrouter.svg",
    categories: ["Frontend"],
    keywords: ["reactrouter", "routing", "react"],
  },
  {
    id: "redhat",
    name: "Red Hat",
    path: "icons/redhat.svg",
    categories: ["Companies"],
    keywords: ["redhat", "linux", "enterprise"],
  },
  {
    id: "redis",
    name: "Redis",
    path: "icons/redis.svg",
    categories: ["Database"],
    keywords: ["redis", "database", "cache"],
  },
  {
    id: "redux-saga",
    name: "Redux-Saga",
    path: "icons/redux-saga.svg",
    categories: ["Frontend"],
    keywords: ["redux-saga", "redux", "effects"],
  },
  {
    id: "redux",
    name: "Redux",
    path: "icons/redux.svg",
    categories: ["Frontend"],
    keywords: ["redux", "state", "react"],
  },
  {
    id: "render",
    name: "Render",
    path: "icons/render.svg",
    categories: ["Backend"],
    keywords: ["render", "hosting", "cloud"],
  },
  {
    id: "resend",
    name: "ReSend",
    path: "icons/resend.svg",
    categories: ["Others"],
    keywords: ["resend", "email", "messaging"],
  },
  {
    id: "rollup",
    name: "Rollup",
    path: "icons/rollup.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["rollup", "javascript", "bundler"],
  },
  {
    id: "ruby",
    name: "Ruby",
    path: "icons/ruby.svg",
    categories: ["Languages"],
    keywords: ["ruby", "programming", "dynamic"],
  },
  {
    id: "rust",
    name: "Rust",
    path: "icons/rust.svg",
    categories: ["Languages"],
    keywords: ["rust", "programming", "systems"],
  },
  {
    id: "safari",
    name: "Safari",
    path: "icons/safari.svg",
    categories: ["Others"],
    keywords: ["safari", "browser", "apple"],
  },
  {
    id: "sass",
    name: "Sass",
    path: "icons/sass.svg",
    categories: ["Frontend", "Design"],
    keywords: ["sass", "css", "stylesheets"],
  },
  {
    id: "scala",
    name: "Scala",
    path: "icons/scala.svg",
    categories: ["Languages"],
    keywords: ["scala", "jvm", "functional"],
  },
  {
    id: "semanticui",
    name: "Semantic UI",
    path: "icons/semanticui.svg",
    categories: ["Frontend", "Design"],
    keywords: ["semanticui", "ui", "design"],
  },
  {
    id: "serverless",
    name: "Serverless",
    path: "icons/serverless.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["serverless", "cloud", "aws"],
  },
  {
    id: "shadcnui",
    name: "Shadcn UI",
    path: "icons/shadcnui.svg",
    categories: ["Others"],
    keywords: ["shadcnui"],
  },
  {
    id: "sketch",
    name: "Sketch",
    path: "icons/sketch.svg",
    categories: ["Design"],
    keywords: ["sketch", "design", "vector"],
  },
  {
    id: "sketch2",
    name: "Sketch 2",
    path: "icons/sketch2.svg",
    categories: ["Design"],
    keywords: ["sketch2", "design", "vector"],
  },
  {
    id: "slack",
    name: "Slack",
    path: "icons/slack.svg",
    categories: ["Productivity"],
    keywords: ["slack", "chat", "team"],
  },
  {
    id: "solidity",
    name: "Solidity",
    path: "icons/solidity.svg",
    categories: ["Languages"],
    keywords: ["solidity", "ethereum", "smart contracts"],
  },
  {
    id: "solidjs",
    name: "SolidJS",
    path: "icons/solidjs.svg",
    categories: ["Frontend"],
    keywords: ["solidjs", "reactive", "ui"],
  },
  {
    id: "spring",
    name: "Spring",
    path: "icons/spring.svg",
    categories: ["Backend"],
    keywords: ["spring", "java", "enterprise"],
  },
  {
    id: "storyblok",
    name: "Storyblok",
    path: "icons/storyblok.svg",
    categories: ["Others"],
    keywords: ["storyblok", "cms", "headless"],
  },
  {
    id: "storybook",
    name: "Storybook",
    path: "icons/storybook.svg",
    categories: ["Design"],
    keywords: ["storybook", "ui", "components"],
  },
  {
    id: "strada",
    name: "Strada",
    path: "icons/strada.svg",
    categories: ["Others"],
    keywords: ["strada"],
  },
  {
    id: "stream",
    name: "Stream",
    path: "icons/stream.svg",
    categories: ["Others"],
    keywords: ["stream", "api", "real-time"],
  },
  {
    id: "stylelint",
    name: "Stylelint",
    path: "icons/stylelint.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["stylelint", "css", "linting"],
  },
  {
    id: "sublime",
    name: "Sublime",
    path: "icons/sublime.svg",
    categories: ["Productivity"],
    keywords: ["sublime", "text editor", "code"],
  },
  {
    id: "supabase",
    name: "Supabase",
    path: "icons/supabase.svg",
    categories: ["Backend", "Database"],
    keywords: ["supabase", "database", "real-time"],
  },
  {
    id: "sveltejs",
    name: "SvelteJS",
    path: "icons/sveltejs.svg",
    categories: ["Frontend"],
    keywords: ["sveltejs", "frontend", "compiler"],
  },
  {
    id: "swagger",
    name: "Swagger",
    path: "icons/swagger.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["swagger", "api", "documentation"],
  },
  {
    id: "swift",
    name: "Swift",
    path: "icons/swift.svg",
    categories: ["Languages"],
    keywords: ["swift", "programming", "apple"],
  },
  {
    id: "tailwindcss",
    name: "Tailwind CSS",
    path: "icons/tailwindcss.svg",
    categories: ["Frontend", "Design"],
    keywords: ["tailwindcss", "utility", "css"],
  },
  {
    id: "threejs",
    name: "Three.js",
    path: "icons/threejs.svg",
    categories: ["Media"],
    keywords: ["threejs", "3d", "webgl"],
  },
  {
    id: "tinyhttp",
    name: "TinyHTTP",
    path: "icons/tinyhttp.svg",
    categories: ["Backend"],
    keywords: ["tinyhttp", "nodejs", "minimalist"],
  },
  {
    id: "tRPC",
    name: "tRPC",
    path: "icons/trpc.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["trpc", "typescript", "rpc"],
  },
  {
    id: "typescript",
    name: "TypeScript",
    path: "icons/typescript.svg",
    categories: ["Languages"],
    keywords: ["typescript", "javascript", "types"],
  },
  {
    id: "ubuntu",
    name: "Ubuntu",
    path: "icons/ubuntu.svg",
    categories: ["Others"],
    keywords: ["ubuntu", "linux", "os"],
  },
  {
    id: "unjs",
    name: "Un.js",
    path: "icons/unjs.svg",
    categories: ["Frontend"],
    keywords: ["unjs", "javascript", "modern"],
  },
  {
    id: "ur",
    name: "UR",
    path: "icons/ur.svg",
    categories: ["Others"],
    keywords: ["ur"],
  },
  {
    id: "vim",
    name: "Vim",
    path: "icons/vim.svg",
    categories: ["Productivity"],
    keywords: ["vim", "editor", "terminal"],
  },
  {
    id: "visualbasic",
    name: "Visual Basic",
    path: "icons/visualbasic.svg",
    categories: ["Languages"],
    keywords: ["visualbasic", "basic", "microsoft"],
  },
  {
    id: "vitejs",
    name: "ViteJS",
    path: "icons/vitejs.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["vitejs", "builder", "frontend"],
  },
  {
    id: "vitest",
    name: "Vitest",
    path: "icons/vitest.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["vitest", "testing", "javascript"],
  },
  {
    id: "vscode",
    name: "Visual Studio Code",
    path: "icons/vscode.svg",
    categories: ["Productivity"],
    keywords: ["vscode", "editor", "microsoft"],
  },
  {
    id: "vuejs",
    name: "Vue.js",
    path: "icons/vuejs.svg",
    categories: ["Frontend"],
    keywords: ["vuejs", "frontend", "framework"],
  },
  {
    id: "webassembly",
    name: "WebAssembly",
    path: "icons/webassembly.svg",
    categories: ["Others"],
    keywords: ["webassembly", "wasm", "web"],
  },
  {
    id: "webpack",
    name: "Webpack",
    path: "icons/webpack.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["webpack", "javascript", "bundler"],
  },
  {
    id: "wordpress",
    name: "WordPress",
    path: "icons/wordpress.svg",
    categories: ["Others"],
    keywords: ["wordpress", "cms", "blog"],
  },
  {
    id: "xamarin",
    name: "Xamarin",
    path: "icons/xamarin.svg",
    categories: ["Native App"],
    keywords: ["xamarin", "mobile", "c#"],
  },
  {
    id: "xd",
    name: "Adobe XD",
    path: "icons/xd.svg",
    categories: ["Design"],
    keywords: ["xd", "adobe", "ux/ui"],
  },
  {
    id: "yoga",
    name: "Yoga",
    path: "icons/yoga.svg",
    categories: ["Others"],
    keywords: ["yoga", "layout", "facebook"],
  },
  {
    id: "zod",
    name: "Zod",
    path: "icons/zod.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["zod", "validation", "typescript"],
  },
];

type Category = (typeof categoriesData)[number];

interface IconDataType {
  id: string;
  name: string;
  path: string;
  categories: Category[];
  keywords: string[];
}
