export const categoriesData = [
  "Languages",
  "Frontend",
  "Backend",
  "Database",
  "Design",
  "Native App",
  "DevOps & AI/ML",
  "Productivity",
  "Media",
  "Companies",
  "Browser",
  "Others",
] as const;

export const iconsData: IconDataType[] = [
  {
    id: "xd",
    name: "Adobe XD",
    path: "icons/xd.svg",
    categories: ["Design"],
    keywords: ["xd", "adobe", "ux/ui"],
    url: "https://adobe.com/products/xd.html",
  },
  {
    id: "android",
    name: "Android",
    path: "icons/android.svg",
    categories: ["Native App"],
    keywords: ["android", "mobile", "google", "app"],
    url: "https://www.android.com",
  },
  {
    id: "angular",
    name: "Angular",
    path: "icons/angular.svg",
    categories: ["Frontend"],
    keywords: ["angular", "frontend", "framework"],
    url: "https://angular.dev",
  },
  {
    id: "ansible",
    name: "Ansible",
    path: "icons/ansible.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["ansible", "automation", "devops"],
    url: "https://www.ansible.com",
  },
  {
    id: "ansible-wordmark",
    name: "Ansible Wordmark",
    path: "icons/ansible-wordmark.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["ansible", "automation", "devops"],
    url: "https://www.ansible.com",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    path: "icons/anthropic.svg",
    categories: ["Companies", "DevOps & AI/ML"],
    keywords: ["anthropic", "ai", "company"],
    url: "https://anthropic.com",
  },
  {
    id: "anthropic-basic-dark",
    name: "Anthropic Basic Dark",
    path: "icons/anthropic-basic-dark.svg",
    categories: ["Companies", "DevOps & AI/ML"],
    keywords: ["anthropic", "ai", "dark"],
    url: "https://anthropic.com",
  },
  {
    id: "anthropic-basic-light",
    name: "Anthropic Basic Light",
    path: "icons/anthropic-basic-light.svg",
    categories: ["Companies", "DevOps & AI/ML"],
    keywords: ["anthropic", "ai", "light"],
    url: "https://anthropic.com",
  },
  {
    id: "apache",
    name: "Apache",
    path: "icons/apache.svg",
    categories: ["Backend"],
    keywords: ["apache", "server", "web"],
    url: "https://apache.org",
  },
  {
    id: "apple-dark",
    name: "Apple Dark",
    path: "icons/apple-dark.svg",
    categories: ["Companies", "Native App"],
    keywords: ["apple", "ios", "dark"],
    url: "https://apple.com",
  },
  {
    id: "apple-light",
    name: "Apple Light",
    path: "icons/apple-light.svg",
    categories: ["Companies", "Native App"],
    keywords: ["apple", "ios", "light"],
    url: "https://apple.com",
  },
  {
    id: "appwrite",
    name: "Appwrite",
    path: "icons/appwrite.svg",
    categories: ["Backend", "Database"],
    keywords: ["appwrite", "backend", "database"],
    url: "https://appwrite.io",
  },
  {
    id: "arc",
    name: "ARC",
    path: "icons/arc.svg",
    categories: ["Browser"],
    keywords: ["arc", "web", "development"],
    url: "https://arc.io",
  },
  {
    id: "astro",
    name: "Astro",
    path: "icons/astro.svg",
    categories: ["Frontend"],
    keywords: ["astro", "frontend", "framework"],
    url: "https://astro.build",
  },
  {
    id: "atlassian",
    name: "Atlassian",
    path: "icons/atlassian.svg",
    categories: ["Productivity"],
    keywords: ["atlassian", "tools", "collaboration"],
    url: "https://atlassian.com",
  },
  {
    id: "atom",
    name: "Atom",
    path: "icons/atom.svg",
    categories: ["Productivity"],
    keywords: ["atom", "editor", "code"],
    url: "https://atom.io",
  },
  {
    id: "auth0",
    name: "Auth0",
    path: "icons/auth0.svg",
    categories: ["Backend"],
    keywords: ["auth0", "authentication", "security"],
    url: "https://auth0.com",
  },
  {
    id: "avajs",
    name: "AVA",
    path: "icons/avajs.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["avajs", "testing", "javascript", "js"],
    url: "https://ava.li",
  },
  {
    id: "aws",
    name: "AWS",
    path: "icons/aws.svg",
    categories: ["Backend", "DevOps & AI/ML"],
    keywords: ["aws", "cloud", "amazon"],
    url: "https://aws.amazon.com",
  },
  {
    id: "axiom",
    name: "Axiom",
    path: "icons/axiom.svg",
    categories: ["Others"],
    keywords: ["axiom", "data", "analysis"],
    url: "https://axiom.co",
  },
  {
    id: "axure",
    name: "Axure",
    path: "icons/axure.svg",
    categories: ["Design"],
    keywords: ["axure", "design", "prototyping"],
    url: "https://axure.com",
  },
  {
    id: "azure",
    name: "Azure",
    path: "icons/azure.svg",
    categories: ["Backend", "DevOps & AI/ML"],
    keywords: ["azure", "microsoft", "cloud"],
    url: "https://azure.microsoft.com",
  },
  {
    id: "babel",
    name: "Babel",
    path: "icons/babel.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["babel", "javascript", "js", "compiler"],
    url: "https://babeljs.io",
  },
  {
    id: "backbonejs",
    name: "Backbone.js",
    path: "icons/backbonejs.svg",
    categories: ["Frontend"],
    keywords: ["backbonejs", "frontend", "framework"],
    url: "https://backbonejs.org",
  },
  {
    id: "bash",
    name: "Bash",
    path: "icons/bash.svg",
    categories: ["Others"],
    keywords: ["bash", "shell", "scripting"],
    url: "https://gnu.org/software/bash",
  },
  {
    id: "bing",
    name: "Bing",
    path: "icons/bing.svg",
    categories: ["Browser"],
    keywords: ["bing", "search", "microsoft"],
    url: "https://bing.com",
  },
  {
    id: "biome",
    name: "Biome",
    path: "icons/biome.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["biome", "code", "javascript", "js", "linting"],
    url: "https://biomejs.dev/",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    path: "icons/bitbucket.svg",
    categories: ["Productivity"],
    keywords: ["bitbucket", "git", "version control"],
    url: "https://bitbucket.org",
  },
  {
    id: "bitnami",
    name: "Bitnami",
    path: "icons/bitnami.svg",
    categories: ["Backend", "DevOps & AI/ML"],
    keywords: ["bitnami", "cloud", "stacks"],
    url: "https://bitnami.com",
  },
  {
    id: "blueprintjs",
    name: "Blueprint.js",
    path: "icons/blueprintjs.svg",
    categories: ["Frontend"],
    keywords: ["blueprintjs", "ui", "react"],
    url: "https://blueprintjs.com",
  },
  {
    id: "bluesky",
    name: "Bluesky",
    path: "icons/bluesky.svg",
    categories: ["Media"],
    keywords: ["blue", "blueskys", "social"],
    url: "https://bsky.app/",
  },
  {
    id: "bootstrap4",
    name: "Bootstrap 4",
    path: "icons/bootstrap4.svg",
    categories: ["Frontend", "Design"],
    keywords: ["bootstrap4", "css", "frontend"],
    url: "https://getbootstrap.com",
  },
  {
    id: "bootstrap5",
    name: "Bootstrap 5",
    path: "icons/bootstrap5.svg",
    categories: ["Frontend", "Design"],
    keywords: ["bootstrap5", "css", "frontend"],
    url: "https://getbootstrap.com",
  },
  {
    id: "brave",
    name: "Brave",
    path: "icons/brave.svg",
    categories: ["Browser"],
    keywords: ["brave", "web", "browser", "privacy"],
    url: "https://brave.com",
  },
  {
    id: "bulmaui",
    name: "Bulma UI",
    path: "icons/bulmaui.svg",
    categories: ["Frontend", "Design"],
    keywords: ["bulmaui", "css", "frontend"],
    url: "https://bulma.io",
  },
  {
    id: "bunjs",
    name: "Bun.js",
    path: "icons/bunjs.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["bunjs", "javascript", "js", "runtime"],
    url: "https://bun.sh",
  },
  {
    id: "c",
    name: "C",
    path: "icons/c.svg",
    categories: ["Languages"],
    keywords: ["c", "programming"],
    url: "https://devdocs.io/c/",
  },
  {
    id: "c-sharp",
    name: "C#",
    path: "icons/c-sharp.svg",
    categories: ["Languages"],
    keywords: ["c-sharp", "programming", "microsoft", "c#"],
    url: "https://docs.microsoft.com/en-us/dotnet/csharp/",
  },
  {
    id: "c-plus-plus",
    name: "C++",
    path: "icons/c-plus-plus.svg",
    categories: ["Languages"],
    keywords: ["c++", "programming", "performance"],
    url: "https://cplusplus.com",
  },
  {
    id: "cakephp",
    name: "CakePHP",
    path: "icons/cakephp.svg",
    categories: ["Backend"],
    keywords: ["cakephp", "php", "framework"],
    url: "https://cakephp.org",
  },
  {
    id: "canva",
    name: "Canva",
    path: "icons/canva.svg",
    categories: ["Design"],
    keywords: ["canva", "design", "graphics"],
    url: "https://canva.com",
  },
  {
    id: "cassandradb",
    name: "Cassandra DB",
    path: "icons/cassandradb.svg",
    categories: ["Database"],
    keywords: ["cassandradb", "database", "nosql"],
    url: "https://cassandra.apache.org",
  },
  {
    id: "chakraui",
    name: "Chakra UI",
    path: "icons/chakraui.svg",
    categories: ["Frontend", "Design"],
    keywords: ["chakraui", "ui", "react"],
    url: "https://chakra-ui.com",
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    path: "icons/chatgpt.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["chatgpt", "ai", "openai"],
    url: "https://openai.com/chatgpt",
  },
  {
    id: "chrome",
    name: "Chrome",
    path: "icons/chrome.svg",
    categories: ["Browser"],
    keywords: ["chrome", "browser", "google"],
    url: "https://google.com/chrome",
  },
  {
    id: "chromium",
    name: "Chromium",
    path: "icons/chromium.svg",
    categories: ["Browser"],
    keywords: ["chromium", "browser", "opensource"],
    url: "https://chromium.org",
  },
  {
    id: "circleci",
    name: "CircleCI",
    path: "icons/circleci.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["circleci", "ci", "cd"],
    url: "https://circleci.com",
  },
  {
    id: "claude-ai",
    name: "Claude AI",
    path: "icons/claude-ai.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["claude", "ai", "chatbot"],
    url: "https://anthropic.com/claude",
  },
  {
    id: "clerk",
    name: "Clerk",
    path: "icons/clerk.svg",
    categories: ["Backend"],
    keywords: ["clerk", "auth", "user management"],
    url: "https://clerk.com/",
  },
  {
    id: "clickhouse",
    name: "ClickHouse",
    path: "icons/clickhouse.svg",
    categories: ["Database"],
    keywords: ["clickhouse", "database", "analytics"],
    url: "https://clickhouse.com",
  },
  {
    id: "clojure",
    name: "Clojure",
    path: "icons/clojure.svg",
    categories: ["Languages"],
    keywords: ["clojure", "functional", "jvm"],
    url: "https://clojure.org",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    path: "icons/cloudflare.svg",
    categories: ["Others"],
    keywords: ["cloudflare", "security", "cdn"],
    url: "https://cloudflare.com",
  },
  {
    id: "cloudinary",
    name: "Cloudinary",
    path: "icons/cloudinary.svg",
    categories: ["Media"],
    keywords: ["cloudinary", "media", "cloud"],
    url: "https://cloudinary.com",
  },
  {
    id: "codefresh",
    name: "Codefresh",
    path: "icons/codefresh.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["codefresh", "ci", "cd"],
    url: "https://codefresh.io",
  },
  {
    id: "codeigniter",
    name: "CodeIgniter",
    path: "icons/codeigniter.svg",
    categories: ["Backend"],
    keywords: ["codeigniter", "php", "framework"],
    url: "https://codeigniter.com",
  },
  {
    id: "convex",
    name: "Convex",
    path: "icons/convex.svg",
    categories: ["Backend", "Database"],
    keywords: ["convex", "auth"],
    url: "https://www.convex.dev/",
  },
  {
    id: "copilot",
    name: "Copilot",
    path: "icons/copilot.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["copilot", "ai", "coding"],
    url: "https://github.com/features/copilot",
  },
  {
    id: "crystal",
    name: "Crystal",
    path: "icons/crystal.svg",
    categories: ["Languages"],
    keywords: ["crystal", "programming", "performance"],
    url: "https://crystal-lang.org",
  },
  {
    id: "css",
    name: "CSS",
    path: "icons/css.svg",
    categories: ["Frontend", "Design"],
    keywords: ["css", "design", "stylesheets"],
    url: "https://w3.org/Style/CSS/",
  },
  {
    id: "css3",
    name: "CSS3",
    path: "icons/css3.svg",
    categories: ["Frontend", "Design"],
    keywords: ["css3", "design", "stylesheets"],
    url: "https://w3.org/Style/CSS/",
  },
  {
    id: "cypress",
    name: "Cypress",
    path: "icons/cypress.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["cypress", "testing", "javascript", "js"],
    url: "https://cypress.io",
  },
  {
    id: "dlang",
    name: "D Language",
    path: "icons/dlang.svg",
    categories: ["Languages"],
    keywords: ["dlang", "programming", "performance"],
    url: "https://dlang.org",
  },
  {
    id: "dart",
    name: "Dart",
    path: "icons/dart.svg",
    categories: ["Languages"],
    keywords: ["dart", "programming", "app development"],
    url: "https://dart.dev",
  },
  {
    id: "datadog",
    name: "Datadog",
    path: "icons/datadog.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["datadog", "monitoring", "analytics"],
    url: "https://datadoghq.com",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    path: "icons/deepseek.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["deepseek", "chat", "ai"],
    url: "https://www.deepseek.com",
  },
  {
    id: "deepseek-wordmark",
    name: "DeepSeek Wordmark",
    path: "icons/deepseek-wordmark.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["deepseek", "chat", "ai"],
    url: "https://www.deepseek.com",
  },
  {
    id: "deno",
    name: "Deno",
    path: "icons/deno.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["deno", "javascript", "js", "typescript"],
    url: "https://deno.land",
  },
  {
    id: "deno-fresh",
    name: "Deno Fresh",
    path: "icons/deno-fresh.svg",
    categories: ["Frontend"],
    keywords: ["deno", "fresh", "frontend", "ssr"],
    url: "https://fresh.deno.dev",
  },
  {
    id: "developer-icons",
    name: "Developer Icons",
    path: "icons/developer-icons.svg",
    categories: ["Frontend", "Design"],
    keywords: ["library", "icons", "react"],
    url: "https://xandemon.github.io/developer-icons",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    path: "icons/digitalocean.svg",
    categories: ["Backend"],
    keywords: ["digitalocean", "cloud", "servers"],
    url: "https://digitalocean.com",
  },
  {
    id: "discord",
    name: "Discord",
    path: "icons/discord.svg",
    categories: ["Productivity"],
    keywords: ["discord", "chat", "voice"],
    url: "https://discord.com",
  },
  {
    id: "django",
    name: "Django",
    path: "icons/django.svg",
    categories: ["Backend"],
    keywords: ["django", "python", "web"],
    url: "https://djangoproject.com",
  },
  {
    id: "docker",
    name: "Docker",
    path: "icons/docker.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["docker", "containers", "devops"],
    url: "https://docker.com",
  },
  {
    id: "doctrine",
    name: "Doctrine",
    path: "icons/doctrine.svg",
    categories: ["Backend", "Database"],
    keywords: ["php", "library", "open source"],
    url: "https://doctrine-project.org",
  },
  {
    id: "docusaurus",
    name: "Docusaurus",
    path: "icons/docusaurus.svg",
    categories: ["Others"],
    keywords: ["docusaurus", "documentation", "static site"],
    url: "https://docusaurus.io",
  },
  {
    id: "dovetail",
    name: "Dovetail",
    path: "icons/dovetail.svg",
    categories: ["Design"],
    keywords: ["dovetail", "design", "prototyping"],
    url: "https://dovetailapp.com",
  },
  {
    id: "ec2",
    name: "EC2",
    path: "icons/ec2.svg",
    categories: ["Backend"],
    keywords: ["ec2", "aws", "cloud"],
    url: "https://aws.amazon.com/ec2",
  },
  {
    id: "edge",
    name: "Edge",
    path: "icons/edge.svg",
    categories: ["Browser"],
    keywords: ["edge", "browser", "microsoft"],
    url: "https://microsoft.com/edge",
  },
  {
    id: "elastic",
    name: "Elastic",
    path: "icons/elastic.svg",
    categories: ["Database"],
    keywords: ["elastic", "search", "elasticsearch"],
    url: "https://elastic.co",
  },
  {
    id: "electron",
    name: "Electron",
    path: "icons/electron.svg",
    categories: ["Native App"],
    keywords: ["electron", "desktop", "apps"],
    url: "https://electronjs.org",
  },
  {
    id: "elementui",
    name: "Element UI",
    path: "icons/elementui.svg",
    categories: ["Frontend", "Design"],
    keywords: ["elementui", "ui", "vue"],
    url: "https://element.eleme.io",
  },
  {
    id: "elixir",
    name: "Elixir",
    path: "icons/elixir.svg",
    categories: ["Languages"],
    keywords: ["elixir", "functional", "concurrent"],
    url: "https://elixir-lang.org",
  },
  {
    id: "ember",
    name: "Ember",
    path: "icons/ember.svg",
    categories: ["Frontend"],
    keywords: ["ember", "frontend", "framework"],
    url: "https://emberjs.com",
  },
  {
    id: "erlang",
    name: "Erlang",
    path: "icons/erlang.svg",
    categories: ["Languages"],
    keywords: ["erlang", "functional", "concurrent"],
    url: "https://erlang.org",
  },
  {
    id: "esbuild",
    name: "esbuild",
    path: "icons/esbuild.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["esbuild", "javascript", "js", "builder"],
    url: "https://esbuild.github.io",
  },
  {
    id: "eslint",
    name: "ESLint",
    path: "icons/eslint.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["eslint", "javascript", "js", "linting"],
    url: "https://eslint.org",
  },
  {
    id: "expressjs-dark",
    name: "Express.js Dark",
    path: "icons/expressjs-dark.svg",
    categories: ["Backend"],
    keywords: ["expressjs", "javascript", "js", "framework", "dark"],
    url: "https://expressjs.com",
  },
  {
    id: "expressjs-light",
    name: "Express.js Light",
    path: "icons/expressjs-light.svg",
    categories: ["Backend"],
    keywords: ["expressjs", "javascript", "js", "framework", "light"],
    url: "https://expressjs.com",
  },
  {
    id: "facebook",
    name: "Facebook",
    path: "icons/facebook.svg",
    categories: ["Media"],
    keywords: ["facebook", "social", "network", "meta"],
    url: "https://facebook.com",
  },
  {
    id: "fast-api",
    name: "FastAPI",
    path: "icons/fast-api.svg",
    categories: ["Backend"],
    keywords: ["fastapi", "python", "framework", "backend"],
    url: "https://fastapi.tiangolo.com",
  },
  {
    id: "faunadb",
    name: "FaunaDB",
    path: "icons/faunadb.svg",
    categories: ["Database"],
    keywords: ["faunadb", "database", "nosql"],
    url: "https://fauna.com",
  },
  {
    id: "figma",
    name: "Figma",
    path: "icons/figma.svg",
    categories: ["Design"],
    keywords: ["figma", "design", "ui"],
    url: "https://figma.com",
  },
  {
    id: "firebase",
    name: "Firebase",
    path: "icons/firebase.svg",
    categories: ["Backend", "Database"],
    keywords: ["firebase", "database", "google"],
    url: "https://firebase.google.com",
  },
  {
    id: "firefox",
    name: "Firefox",
    path: "icons/firefox.svg",
    categories: ["Browser"],
    keywords: ["firefox", "browser", "mozilla"],
    url: "https://mozilla.org/firefox",
  },
  {
    id: "flask-dark",
    name: "Flask Dark",
    path: "icons/flask-dark.svg",
    categories: ["Backend"],
    keywords: ["flask-dark", "python", "web"],
    url: "https://palletsprojects.com/p/flask/",
  },
  {
    id: "flask-light",
    name: "Flask Light",
    path: "icons/flask-light.svg",
    categories: ["Backend"],
    keywords: ["flask", "python", "web"],
    url: "https://palletsprojects.com/p/flask/",
  },
  {
    id: "flutter",
    name: "Flutter",
    path: "icons/flutter.svg",
    categories: ["Native App"],
    keywords: ["flutter", "mobile", "apps"],
    url: "https://flutter.dev",
  },
  {
    id: "flyio",
    name: "Fly.io",
    path: "icons/flyio.svg",
    categories: ["Backend"],
    keywords: ["flyio", "hosting", "cloud"],
    url: "https://fly.io",
  },
  {
    id: "framer-dark",
    name: "Framer-Dark",
    path: "icons/framer-dark.svg",
    categories: ["Design"],
    keywords: ["framer", "design", "prototyping"],
    url: "https://framer.com",
  },
  {
    id: "framer-light",
    name: "Framer-Light",
    path: "icons/framer-light.svg",
    categories: ["Design"],
    keywords: ["framer", "design", "prototyping"],
    url: "https://framer.com",
  },
  {
    id: "gatsby",
    name: "Gatsby",
    path: "icons/gatsby.svg",
    categories: ["Frontend"],
    keywords: ["gatsby", "react", "static site"],
    url: "https://gatsbyjs.com",
  },
  {
    id: "git",
    name: "Git",
    path: "icons/git.svg",
    categories: ["Productivity"],
    keywords: ["git", "version control", "code"],
    url: "https://git-scm.com",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    path: "icons/github-copilot.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["github-copilot", "ai", "coding"],
    url: "https://copilot.github.com",
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    path: "icons/github-dark.svg",
    categories: ["Productivity"],
    keywords: ["github", "git", "repository"],
    url: "https://github.com",
  },
  {
    id: "github-light",
    name: "GitHub Light",
    path: "icons/github-light.svg",
    categories: ["Productivity"],
    keywords: ["github", "git", "repository"],
    url: "https://github.com",
  },
  {
    id: "gitlab",
    name: "GitLab",
    path: "icons/gitlab.svg",
    categories: ["Productivity"],
    keywords: ["gitlab", "git", "ci/cd"],
    url: "https://gitlab.com",
  },
  {
    id: "gmail",
    name: "Gmail",
    path: "icons/gmail.svg",
    categories: ["Productivity"],
    keywords: ["gmail", "email", "google"],
    url: "https://mail.google.com",
  },
  {
    id: "go",
    name: "Go",
    path: "icons/go.svg",
    categories: ["Languages"],
    keywords: ["go", "programming", "google"],
    url: "https://golang.org",
  },
  {
    id: "google",
    name: "Google",
    path: "icons/google.svg",
    categories: ["Browser", "Companies"],
    keywords: ["google", "search", "internet"],
    url: "https://google.com",
  },
  {
    id: "google-cloud",
    name: "Google Cloud",
    path: "icons/google-cloud.svg",
    categories: ["Backend", "DevOps & AI/ML"],
    keywords: ["google-cloud", "cloud", "google"],
    url: "https://cloud.google.com",
  },
  {
    id: "google-wordmark",
    name: "Google Wordmark",
    path: "icons/google-wordmark.svg",
    categories: ["Browser", "Companies"],
    keywords: ["google", "search", "internet"],
    url: "https://google.com",
  },
  {
    id: "grafana",
    name: "Grafana",
    path: "icons/grafana.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["grafana", "monitoring", "metrics"],
    url: "https://grafana.com",
  },
  {
    id: "grafbase",
    name: "Grafbase",
    path: "icons/grafbase.svg",
    categories: ["Database"],
    keywords: ["grafbase", "graphql", "database"],
    url: "https://grafbase.com",
  },
  {
    id: "graphite",
    name: "Graphite",
    path: "icons/graphite.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["graphite", "monitoring", "metrics"],
    url: "https://graphiteapp.org",
  },
  {
    id: "graphql",
    name: "GraphQL",
    path: "icons/graphql.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["graphql", "api", "query"],
    url: "https://graphql.org",
  },
  {
    id: "gridsome",
    name: "Gridsome",
    path: "icons/gridsome.svg",
    categories: ["Frontend"],
    keywords: ["gridsome", "vue", "static site"],
    url: "https://gridsome.org",
  },
  {
    id: "gruntjs",
    name: "Grunt.js",
    path: "icons/gruntjs.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["gruntjs", "javascript", "js", "task"],
    url: "https://gruntjs.com",
  },
  {
    id: "gulp",
    name: "Gulp",
    path: "icons/gulp.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["gulp", "javascript", "js", "task"],
    url: "https://gulpjs.com",
  },
  {
    id: "hashnode",
    name: "Hashnode",
    path: "icons/hashnode.svg",
    categories: ["Media"],
    keywords: ["hashnode", "blogging", "community"],
    url: "https://hashnode.com",
  },
  {
    id: "haskell",
    name: "Haskell",
    path: "icons/haskell.svg",
    categories: ["Languages"],
    keywords: ["haskell", "functional", "programming"],
    url: "https://haskell.org",
  },
  {
    id: "headlessui",
    name: "Headless UI",
    path: "icons/headlessui.svg",
    categories: ["Frontend", "Design"],
    keywords: ["headlessui", "ui", "tailwind"],
    url: "https://headlessui.dev",
  },
  {
    id: "heroku",
    name: "Heroku",
    path: "icons/heroku.svg",
    categories: ["Backend"],
    keywords: ["heroku", "cloud", "hosting"],
    url: "https://heroku.com",
  },
  {
    id: "hexo",
    name: "Hexo",
    path: "icons/hexo.svg",
    categories: ["Others"],
    keywords: ["hexo", "static site", "nodejs"],
    url: "https://hexo.io",
  },
  {
    id: "hhvm",
    name: "HHVM",
    path: "icons/hhvm.svg",
    categories: ["Others"],
    keywords: ["hhvm", "virtual machine", "php"],
    url: "https://hhvm.com",
  },
  {
    id: "homebrew",
    name: "Homebrew",
    path: "icons/homebrew.svg",
    categories: ["Others"],
    keywords: ["homebrew", "macos", "linux"],
    url: "https://brew.sh",
  },
  {
    id: "hotjar",
    name: "Hotjar",
    path: "icons/hotjar.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["hotjar", "analytics", "user behavior"],
    url: "https://hotjar.com",
  },
  {
    id: "html5",
    name: "HTML5",
    path: "icons/html5.svg",
    categories: ["Frontend", "Design"],
    keywords: ["html5", "markup", "web"],
    url: "https://html.spec.whatwg.org/",
  },
  {
    id: "hugging-face",
    name: "Hugging Face",
    path: "icons/hugging-face.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["hugging-face", "ai", "machine learning"],
    url: "https://huggingface.co/",
  },
  {
    id: "hyper2",
    name: "Hyper 2",
    path: "icons/hyper2.svg",
    categories: ["Productivity"],
    keywords: ["hyper2", "terminal", "shell"],
    url: "https://hyper.is",
  },
  {
    id: "i18next",
    name: "i18next",
    path: "icons/i18next.svg",
    categories: ["Others"],
    keywords: ["i18next", "i18n", "localization"],
    url: "https://i18next.com",
  },
  {
    id: "indesign",
    name: "InDesign",
    path: "icons/indesign.svg",
    categories: ["Design"],
    keywords: ["indesign", "adobe", "layout"],
    url: "https://adobe.com/products/indesign.html",
  },
  {
    id: "insomnia",
    name: "Insomnia",
    path: "icons/insomnia.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["insomnia", "api", "testing"],
    url: "https://insomnia.rest",
  },
  {
    id: "instagram",
    name: "Instagram",
    path: "icons/instagram.svg",
    categories: ["Media"],
    keywords: ["instagram", "social", "media"],
    url: "https://instagram.com",
  },
  {
    id: "internet-explorer",
    name: "Internet Explorer",
    path: "icons/internet-explorer.svg",
    categories: ["Browser"],
    keywords: ["internet-explorer", "browser", "microsoft"],
    url: "https://support.microsoft.com/en-us/internet-explorer",
  },
  {
    id: "invision",
    name: "InVision",
    path: "icons/invision.svg",
    categories: ["Design"],
    keywords: ["invision", "design", "prototyping"],
    url: "https://invisionapp.com",
  },
  {
    id: "ionic",
    name: "Ionic",
    path: "icons/ionic.svg",
    categories: ["Native App"],
    keywords: ["ionic", "mobile", "hybrid"],
    url: "https://ionicframework.com",
  },
  {
    id: "jamstack",
    name: "JAMstack",
    path: "icons/jamstack.svg",
    categories: ["Others"],
    keywords: ["jamstack", "static site", "web"],
    url: "https://jamstack.org",
  },
  {
    id: "java",
    name: "Java",
    path: "icons/java.svg",
    categories: ["Languages"],
    keywords: ["java", "programming", "jvm"],
    url: "https://oracle.com/java/",
  },
  {
    id: "javascript",
    name: "JavaScript",
    path: "icons/javascript.svg",
    categories: ["Languages"],
    keywords: ["javascript", "js", "programming", "web"],
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  },
  {
    id: "jenkins",
    name: "Jenkins",
    path: "icons/jenkins.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["jenkins", "ci", "cd"],
    url: "https://www.jenkins.io",
  },
  {
    id: "jest",
    name: "Jest",
    path: "icons/jest.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["jest", "testing", "javascript", "js"],
    url: "https://jestjs.io",
  },
  {
    id: "jira",
    name: "Jira",
    path: "icons/jira.svg",
    categories: ["Productivity"],
    keywords: ["jira", "atlassian", "project management"],
    url: "https://atlassian.com/software/jira",
  },
  {
    id: "jquery",
    name: "jQuery",
    path: "icons/jquery.svg",
    categories: ["Frontend"],
    keywords: ["jquery", "javascript", "js", "library"],
    url: "https://jquery.com",
  },
  {
    id: "jslint",
    name: "JSLint",
    path: "icons/jslint.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["jslint", "javascript", "js", "linting"],
    url: "https://jslint.com",
  },
  {
    id: "json",
    name: "JSON",
    path: "icons/json.svg",
    categories: ["Others"],
    keywords: ["json", "data", "format"],
    url: "https://json.org",
  },
  {
    id: "kafka",
    name: "Kafka",
    path: "icons/kafka.svg",
    categories: ["Backend"],
    keywords: ["kafka", "apache"],
    url: "https://kafka.apache.org/",
  },
  {
    id: "k6",
    name: "K6",
    path: "icons/k6.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["k6", "testing", "load testing", "open source", "grafana"],
    url: "https://k6.io/",
  },
  {
    id: "kibana",
    name: "Kibana",
    path: "icons/kibana.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["kibana", "elasticsearch", "dashboard"],
    url: "https://elastic.co/kibana",
  },
  {
    id: "kotlin",
    name: "Kotlin",
    path: "icons/kotlin.svg",
    categories: ["Languages"],
    keywords: ["kotlin", "programming", "jvm"],
    url: "https://kotlinlang.org",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    path: "icons/kubernetes.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["kubernetes", "containers", "orchestration"],
    url: "https://kubernetes.io",
  },
  {
    id: "laravel",
    name: "Laravel",
    path: "icons/laravel.svg",
    categories: ["Backend"],
    keywords: ["laravel", "php", "web"],
    url: "https://laravel.com",
  },
  {
    id: "lerna-dark",
    name: "Lerna Dark",
    path: "icons/lerna-dark.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["lerna", "package manager", "nodejs", "monorepo", "javascript"],
    url: "https://lerna.js.org",
  },
  {
    id: "lerna-light",
    name: "Lerna Light",
    path: "icons/lerna-light.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["lerna", "package manager", "nodejs", "monorepo", "javascript"],
    url: "https://lerna.js.org",
  },
  {
    id: "less",
    name: "Less",
    path: "icons/less.svg",
    categories: ["Frontend", "Design"],
    keywords: ["less", "css", "preprocessor"],
    url: "https://lesscss.org",
  },
  {
    id: "lightroom",
    name: "Lightroom",
    path: "icons/lightroom.svg",
    categories: ["Design"],
    keywords: ["lightroom", "adobe", "photo editing"],
    url: "https://adobe.com/products/photoshop-lightroom.html",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    path: "icons/linkedin.svg",
    categories: ["Media"],
    keywords: ["linkedin", "social", "network"],
    url: "https://linkedin.com",
  },
  {
    id: "linux",
    name: "Linux",
    path: "icons/linux.svg",
    categories: ["DevOps & AI/ML", "Native App"],
    keywords: ["linux", "os", "open source"],
    url: "https://kernel.org",
  },
  {
    id: "lit",
    name: "Lit",
    path: "icons/lit.svg",
    categories: ["Frontend"],
    keywords: ["lit", "web components", "javascript", "js"],
    url: "https://lit.dev",
  },
  {
    id: "liveblocks",
    name: "Liveblocks",
    path: "icons/liveblocks.svg",
    categories: ["Backend"],
    keywords: ["liveblocks", "real-time", "collaboration"],
    url: "https://liveblocks.io",
  },
  {
    id: "logrocket",
    name: "LogRocket",
    path: "icons/logrocket.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["logrocket", "monitoring", "user experience"],
    url: "https://logrocket.com",
  },
  {
    id: "lokalise",
    name: "Lokalise",
    path: "icons/lokalise.svg",
    categories: ["Others"],
    keywords: ["lokalise", "localization", "translation"],
    url: "https://lokalise.com",
  },
  {
    id: "lua",
    name: "Lua",
    path: "icons/lua.svg",
    categories: ["Languages"],
    keywords: ["lua", "scripting", "game development"],
    url: "https://lua.org",
  },
  {
    id: "lunacy",
    name: "Lunacy",
    path: "icons/lunacy.svg",
    categories: ["Design"],
    keywords: ["lunacy", "design", "vector graphics"],
    url: "https://icons8.com/lunacy",
  },
  {
    id: "mariadb",
    name: "MariaDB",
    path: "icons/mariadb.svg",
    categories: ["Database"],
    keywords: ["mariadb", "database", "mysql"],
    url: "https://mariadb.org",
  },
  {
    id: "marionette",
    name: "Marionette",
    path: "icons/marionette.svg",
    categories: ["Frontend"],
    keywords: ["marionette", "javascript", "js", "mvc"],
    url: "https://marionettejs.com",
  },
  {
    id: "markdown",
    name: "Markdown",
    path: "icons/markdown.svg",
    categories: ["Others"],
    keywords: ["markdown", "writing", "documentation"],
    url: "https://daringfireball.net/projects/markdown/",
  },
  {
    id: "mastodon",
    name: "Mastodon",
    path: "icons/mastodon.svg",
    categories: ["Media"],
    keywords: ["mastodon", "social", "network"],
    url: "https://joinmastodon.org",
  },
  {
    id: "materialui",
    name: "Material UI",
    path: "icons/materialui.svg",
    categories: ["Frontend", "Design"],
    keywords: ["materialui", "ui", "react"],
    url: "https://mui.com",
  },
  {
    id: "messenger",
    name: "Messenger",
    path: "icons/messenger.svg",
    categories: ["Media"],
    keywords: ["messenger", "facebook", "chat", "meta"],
    url: "https://messenger.com",
  },
  {
    id: "meta",
    name: "Meta",
    path: "icons/meta.svg",
    categories: ["Companies"],
    keywords: ["meta", "facebook", "social media"],
    url: "https://meta.com",
  },
  {
    id: "microsoft",
    name: "Microsoft",
    path: "icons/microsoft.svg",
    categories: ["Companies"],
    keywords: ["microsoft", "software", "technology"],
    url: "https://microsoft.com",
  },
  {
    id: "microsoft-sql-server",
    name: "Microsoft SQL Server",
    path: "icons/microsoft-sql-server.svg",
    categories: ["Database", "Backend"],
    keywords: ["microsoft-sql-server", "database", "sql", "microsoft"],
    url: "https://www.microsoft.com/en-us/sql-server",
  },
  {
    id: "microsoft-sql-server-2",
    name: "Microsoft SQL Server 2",
    path: "icons/microsoft-sql-server-2.svg",
    categories: ["Database", "Backend"],
    keywords: ["microsoft-sql-server", "database", "sql", "microsoft", "enterprise"],
    url: "https://www.microsoft.com/en-us/sql-server",
  },
  {
    id: "miro",
    name: "Miro",
    path: "icons/miro.svg",
    categories: ["Design"],
    keywords: ["miro", "whiteboard", "collaboration"],
    url: "https://miro.com",
  },
  {
    id: "mochajs",
    name: "MochaJS",
    path: "icons/mochajs.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["mochajs", "testing", "javascript", "js"],
    url: "https://mochajs.org",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    path: "icons/mongodb.svg",
    categories: ["Database"],
    keywords: ["mongodb", "database", "nosql"],
    url: "https://mongodb.com",
  },
  {
    id: "mozilla",
    name: "Mozilla",
    path: "icons/mozilla.svg",
    categories: ["Companies"],
    keywords: ["mozilla", "software", "technology"],
    url: "https://mozilla.org",
  },
  {
    id: "mysql",
    name: "MySQL",
    path: "icons/mysql.svg",
    categories: ["Database"],
    keywords: ["mysql", "database", "sql"],
    url: "https://mysql.com",
  },
  {
    id: "neovim",
    name: "NeoVim",
    path: "icons/neovim.svg",
    categories: ["Productivity"],
    keywords: ["neovim", "editor", "vim"],
    url: "https://neovim.io",
  },
  {
    id: "nestjs",
    name: "NestJS",
    path: "icons/nestjs.svg",
    categories: ["Backend"],
    keywords: ["nestjs", "nodejs", "typescript", "js"],
    url: "https://nestjs.com",
  },
  {
    id: "netlify",
    name: "Netlify",
    path: "icons/netlify.svg",
    categories: ["Backend"],
    keywords: ["netlify", "hosting", "static site"],
    url: "https://netlify.com",
  },
  {
    id: "netlify2",
    name: "Netlify 2",
    path: "icons/netlify2.svg",
    categories: ["Backend"],
    keywords: ["netlify2", "hosting", "static site"],
    url: "https://netlify.com",
  },
  {
    id: "nextjs",
    name: "Next.js",
    path: "icons/nextjs.svg",
    categories: ["Frontend"],
    keywords: ["nextjs", "react", "ssr"],
    url: "https://nextjs.org",
  },
  {
    id: "nextjs-wordmark",
    name: "Next.js Wordmark",
    path: "icons/nextjs-wordmark.svg",
    categories: ["Frontend"],
    keywords: ["nextjs-wordmark", "nextjs", "react"],
    url: "https://nextjs.org",
  },
  {
    id: "nim",
    name: "Nim",
    path: "icons/nim.svg",
    categories: ["Languages"],
    keywords: ["nim", "programming", "efficient"],
    url: "https://nim-lang.org",
  },
  {
    id: "nodejs",
    name: "Node.js",
    path: "icons/nodejs.svg",
    categories: ["Backend"],
    keywords: ["nodejs", "javascript", "js", "server"],
    url: "https://nodejs.org",
  },
  {
    id: "notion",
    name: "Notion",
    path: "icons/notion.svg",
    categories: ["Productivity"],
    keywords: ["notion", "notes", "collaboration", "workspace"],
    url: "https://www.notion.so",
  },
  {
    id: "npm",
    name: "NPM",
    path: "icons/npm.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["npm", "package manager", "nodejs"],
    url: "https://npmjs.com",
  },
  {
    id: "npm-wordmark",
    name: "NPM Wordmark",
    path: "icons/npm-wordmark.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["npm-wordmark", "npm", "javascript", "js"],
    url: "https://npmjs.com",
  },
  {
    id: "numpy",
    name: "NumPy",
    path: "icons/numpy.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["numpy"],
    url: "https://numpy.org/",
  },
  {
    id: "nuxtjs",
    name: "Nuxt.js",
    path: "icons/nuxtjs.svg",
    categories: ["Frontend"],
    keywords: ["nuxtjs", "vue", "ssr"],
    url: "https://nuxtjs.org",
  },
  {
    id: "nx",
    name: "Nx",
    path: "icons/nx.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["nx", "monorepo"],
    url: "https://nx.dev",
  },
  {
    id: "ocaml",
    name: "OCaml",
    path: "icons/ocaml.svg",
    categories: ["Languages"],
    keywords: ["ocaml", "functional", "programming"],
    url: "https://ocaml.org",
  },
  {
    id: "onedrive",
    name: "OneDrive",
    path: "icons/onedrive.svg",
    categories: ["Others"],
    keywords: ["onedrive", "cloud", "microsoft"],
    url: "https://onedrive.live.com",
  },
  {
    id: "openai",
    name: "OpenAI",
    path: "icons/openai.svg",
    categories: ["Companies", "DevOps & AI/ML"],
    keywords: ["openai", "ai", "machine learning"],
    url: "https://openai.com",
  },
  {
    id: "opera",
    name: "Opera",
    path: "icons/opera.svg",
    categories: ["Browser"],
    keywords: ["opera", "browser", "web"],
    url: "https://opera.com",
  },
  {
    id: "oracle",
    name: "Oracle",
    path: "icons/oracle.svg",
    categories: ["Companies", "Database"],
    keywords: ["oracle", "database", "enterprise"],
    url: "https://oracle.com",
  },
  {
    id: "outlook",
    name: "Outlook",
    path: "icons/outlook.svg",
    categories: ["Productivity"],
    keywords: ["outlook", "email", "microsoft"],
    url: "https://outlook.live.com",
  },
  {
    id: "pandacss",
    name: "Panda CSS",
    path: "icons/pandacss.svg",
    categories: ["Frontend", "Design"],
    keywords: ["pandacss", "css", "styling"],
    url: "https://panda-css.com",
  },
  {
    id: "photoshop",
    name: "Photoshop",
    path: "icons/photoshop.svg",
    categories: ["Design"],
    keywords: ["photoshop", "adobe", "graphics"],
    url: "https://adobe.com/products/photoshop.html",
  },
  {
    id: "php",
    name: "PHP",
    path: "icons/php.svg",
    categories: ["Languages", "Backend"],
    keywords: ["php", "web", "backend"],
    url: "https://php.net",
  },
  {
    id: "pinia",
    name: "Pinia",
    path: "icons/pinia.svg",
    categories: ["Frontend"],
    keywords: ["pinia", "state", "vue"],
    url: "https://pinia.vuejs.org",
  },
  {
    id: "pinterest",
    name: "Pinterest",
    path: "icons/pinterest.svg",
    categories: ["Media"],
    keywords: ["pinterest", "social", "images"],
    url: "https://pinterest.com",
  },
  {
    id: "pixijs",
    name: "PixiJS",
    path: "icons/pixijs.svg",
    categories: ["Media"],
    keywords: ["pixijs", "webgl", "rendering"],
    url: "https://pixijs.com",
  },
  {
    id: "playwright",
    name: "Playwright",
    path: "icons/playwright.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["playwright", "testing", "browser"],
    url: "https://playwright.dev",
  },
  {
    id: "pnpm-dark",
    name: "Pnpm Dark",
    path: "icons/pnpm-dark.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["pnpm", "package manager", "nodejs"],
    url: "https://pnpm.io/",
  },
  {
    id: "pnpm-dark-wordmark",
    name: "Pnpm Dark Wordmark",
    path: "icons/pnpm-dark-wordmark.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["pnpm", "package manager", "nodejs"],
    url: "https://pnpm.io/",
  },
  {
    id: "pnpm-light",
    name: "Pnpm Light",
    path: "icons/pnpm-light.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["pnpm", "package manager", "nodejs"],
    url: "https://pnpm.io/",
  },
  {
    id: "pnpm-light-wordmark",
    name: "Pnpm Light Wordmark",
    path: "icons/pnpm-light-wordmark.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["pnpm", "package manager", "nodejs"],
    url: "https://pnpm.io/",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    path: "icons/postgresql.svg",
    categories: ["Database"],
    keywords: ["postgresql", "database", "sql"],
    url: "https://postgresql.org",
  },
  {
    id: "postman",
    name: "Postman",
    path: "icons/postman.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["postman", "api", "testing"],
    url: "https://postman.com",
  },
  {
    id: "powershell",
    name: "PowerShell",
    path: "icons/powershell.svg",
    categories: ["Others"],
    keywords: ["powershell", "shell", "scripting"],
    url: "https://microsoft.com/powershell",
  },
  {
    id: "preact",
    name: "Preact",
    path: "icons/preact.svg",
    categories: ["Frontend"],
    keywords: ["preact", "react", "performance"],
    url: "https://preactjs.com",
  },
  {
    id: "presto",
    name: "Presto",
    path: "icons/presto.svg",
    categories: ["Database"],
    keywords: ["presto", "sql", "analytics"],
    url: "https://prestodb.io",
  },
  {
    id: "prettier",
    name: "Prettier",
    path: "icons/prettier.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["prettier", "code", "formatter"],
    url: "https://prettier.io",
  },
  {
    id: "prisma",
    name: "Prisma",
    path: "icons/prisma.svg",
    categories: ["Backend"],
    keywords: ["prisma", "orm", "database"],
    url: "https://prisma.io",
  },
  {
    id: "pugjs",
    name: "Pug.js",
    path: "icons/pugjs.svg",
    categories: ["Backend"],
    keywords: ["pugjs", "template", "html"],
    url: "https://pugjs.org",
  },
  {
    id: "pulumi",
    name: "Pulumi",
    path: "icons/pulumi.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["pulumi", "automation", "devops"],
    url: "https://www.pulumi.com/",
  },
  {
    id: "pulumi-dark-wordmark",
    name: "Pulumi Dark",
    path: "icons/pulumi-dark-wordmark.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["pulumi", "automation", "devops"],
    url: "https://www.pulumi.com/",
  },
  {
    id: "pulumi-light-wordmark",
    name: "Pulumi Light",
    path: "icons/pulumi-light-wordmark.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["pulumi", "automation", "devops"],
    url: "https://www.pulumi.com/",
  },
  {
    id: "pwa",
    name: "PWA",
    path: "icons/pwa.svg",
    categories: ["Frontend"],
    keywords: ["pwa", "web app", "offline"],
    url: "https://web.dev/progressive-web-apps/",
  },
  {
    id: "python",
    name: "Python",
    path: "icons/python.svg",
    categories: ["Languages"],
    keywords: ["python", "programming", "general purpose"],
    url: "https://python.org",
  },
  {
    id: "pytorch",
    name: "PyTorch",
    path: "icons/pytorch.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["pytorch", "machine learning", "deep learning"],
    url: "https://pytorch.org",
  },
  {
    id: "pytorch3d",
    name: "PyTorch3D",
    path: "icons/pytorch3d.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["pytorch3d", "3d", "machine learning"],
    url: "https://pytorch3d.org",
  },
  {
    id: "qwik",
    name: "Qwik",
    path: "icons/qwik.svg",
    categories: ["Frontend"],
    keywords: ["qwik", "frontend", "performance"],
    url: "https://qwik.builder.io",
  },
  {
    id: "r",
    name: "R",
    path: "icons/r.svg",
    categories: ["Languages"],
    keywords: ["r", "programming", "dynamic", "data science"],
    url: "https://www.r-project.org/",
  },
  {
    id: "radixui",
    name: "Radix UI",
    path: "icons/radixui.svg",
    categories: ["Frontend", "Design"],
    keywords: ["radixui", "ui", "design systems"],
    url: "https://radix-ui.com",
  },
  {
    id: "rails",
    name: "Rails",
    path: "icons/rails.svg",
    categories: ["Backend"],
    keywords: ["rails", "ruby", "web"],
    url: "https://rubyonrails.org",
  },
  {
    id: "railway",
    name: "Railway",
    path: "icons/railway.svg",
    categories: ["Backend"],
    keywords: ["railway", "hosting", "cloud"],
    url: "https://railway.app",
  },
  {
    id: "reactjs",
    name: "React",
    path: "icons/reactjs.svg",
    categories: ["Frontend"],
    keywords: ["reactjs", "ui", "javascript", "js"],
    url: "https://reactjs.org",
  },
  {
    id: "react-query",
    name: "React Query",
    path: "icons/react-query.svg",
    categories: ["Frontend"],
    keywords: ["react-query", "react", "data fetching"],
    url: "https://react-query.tanstack.com",
  },
  {
    id: "reactrouter",
    name: "React Router",
    path: "icons/reactrouter.svg",
    categories: ["Frontend"],
    keywords: ["reactrouter", "routing", "react"],
    url: "https://reactrouter.com",
  },
  {
    id: "redhat",
    name: "Red Hat",
    path: "icons/redhat.svg",
    categories: ["Companies"],
    keywords: ["redhat", "linux", "enterprise"],
    url: "https://redhat.com",
  },
  {
    id: "reddit",
    name: "Reddit",
    path: "icons/reddit.svg",
    categories: ["Media"],
    keywords: ["reddit", "social", "community"],
    url: "https://reddit.com",
  },
  {
    id: "reddit-wordmark",
    name: "Reddit Wordmark",
    path: "icons/reddit-wordmark.svg",
    categories: ["Media"],
    keywords: ["reddit", "social", "community"],
    url: "https://reddit.com",
  },
  {
    id: "redis",
    name: "Redis",
    path: "icons/redis.svg",
    categories: ["Database"],
    keywords: ["redis", "database", "cache"],
    url: "https://redis.io",
  },
  {
    id: "redux",
    name: "Redux",
    path: "icons/redux.svg",
    categories: ["Frontend"],
    keywords: ["redux", "state", "react"],
    url: "https://redux.js.org",
  },
  {
    id: "redux-saga",
    name: "Redux-Saga",
    path: "icons/redux-saga.svg",
    categories: ["Frontend"],
    keywords: ["redux-saga", "redux", "effects"],
    url: "https://redux-saga.js.org",
  },
  {
    id: "remix-dark",
    name: "Remix Dark",
    path: "icons/remix-dark.svg",
    categories: ["Frontend"],
    keywords: ["remix", "react", "framework"],
    url: "https://remix.run",
  },
  {
    id: "remix-dark-wordmark",
    name: "Remix Dark Wordmark",
    path: "icons/remix-dark-wordmark.svg",
    categories: ["Frontend"],
    keywords: ["remix", "react", "framework"],
    url: "https://remix.run",
  },
  {
    id: "remix-light",
    name: "Remix Light",
    path: "icons/remix-light.svg",
    categories: ["Frontend"],
    keywords: ["remix", "react", "framework"],
    url: "https://remix.run",
  },
  {
    id: "remix-light-wordmark",
    name: "Remix Light Wordmark",
    path: "icons/remix-light-wordmark.svg",
    categories: ["Frontend"],
    keywords: ["remix", "react", "framework"],
    url: "https://remix.run",
  },
  {
    id: "render",
    name: "Render",
    path: "icons/render.svg",
    categories: ["Backend"],
    keywords: ["render", "hosting", "cloud"],
    url: "https://render.com",
  },
  {
    id: "resend",
    name: "ReSend",
    path: "icons/resend.svg",
    categories: ["Others"],
    keywords: ["resend", "email", "messaging"],
    url: "https://resend.com",
  },
  {
    id: "rollup",
    name: "Rollup",
    path: "icons/rollup.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["rollup", "javascript", "js", "bundler"],
    url: "https://rollupjs.org",
  },
  {
    id: "ruby",
    name: "Ruby",
    path: "icons/ruby.svg",
    categories: ["Languages"],
    keywords: ["ruby", "programming", "dynamic"],
    url: "https://ruby-lang.org",
  },
  {
    id: "rust-dark",
    name: "Rust Dark",
    path: "icons/rust-dark.svg",
    categories: ["Languages"],
    keywords: ["rust", "programming", "systems"],
    url: "https://rust-lang.org",
  },
  {
    id: "rust-light",
    name: "Rust Light",
    path: "icons/rust-light.svg",
    categories: ["Languages"],
    keywords: ["rust", "programming", "systems"],
    url: "https://rust-lang.org",
  },
  {
    id: "safari",
    name: "Safari",
    path: "icons/safari.svg",
    categories: ["Browser"],
    keywords: ["safari", "browser", "apple"],
    url: "https://apple.com/safari",
  },
  {
    id: "sass",
    name: "Sass",
    path: "icons/sass.svg",
    categories: ["Frontend", "Design"],
    keywords: ["sass", "css", "stylesheets"],
    url: "https://sass-lang.com",
  },
  {
    id: "scala",
    name: "Scala",
    path: "icons/scala.svg",
    categories: ["Languages"],
    keywords: ["scala", "jvm", "functional"],
    url: "https://scala-lang.org",
  },
  {
    id: "semanticui",
    name: "Semantic UI",
    path: "icons/semanticui.svg",
    categories: ["Frontend", "Design"],
    keywords: ["semanticui", "ui", "design"],
    url: "https://semantic-ui.com",
  },
  {
    id: "serverless",
    name: "Serverless",
    path: "icons/serverless.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["serverless", "cloud", "aws"],
    url: "https://serverless.com",
  },
  {
    id: "shadcnui",
    name: "Shadcn UI",
    path: "icons/shadcnui.svg",
    categories: ["Others"],
    keywords: ["shadcnui"],
    url: "https://ui.shadcn.com/",
  },
  {
    id: "shopware",
    name: "Shopware",
    path: "icons/shopware.svg",
    categories: ["Others"],
    keywords: ["shopware", "ecommerce", "platform", "headless", "open source"],
    url: "https://github.com/shopware/shopware",
  },
  {
    id: "sketch",
    name: "Sketch",
    path: "icons/sketch.svg",
    categories: ["Design"],
    keywords: ["sketch", "design", "vector"],
    url: "https://sketch.com",
  },
  {
    id: "sketch2",
    name: "Sketch 2",
    path: "icons/sketch2.svg",
    categories: ["Design"],
    keywords: ["sketch2", "design", "vector"],
    url: "https://sketch.com",
  },
  {
    id: "skype",
    name: "Skype",
    path: "icons/skype.svg",
    categories: ["Media"],
    keywords: ["skype", "communication", "video call"],
    url: "https://skype.com",
  },
  {
    id: "slack",
    name: "Slack",
    path: "icons/slack.svg",
    categories: ["Productivity"],
    keywords: ["slack", "chat", "team"],
    url: "https://slack.com",
  },
  {
    id: "solidity",
    name: "Solidity",
    path: "icons/solidity.svg",
    categories: ["Languages"],
    keywords: ["solidity", "ethereum", "smart contracts"],
    url: "https://soliditylang.org",
  },
  {
    id: "solidjs",
    name: "SolidJS",
    path: "icons/solidjs.svg",
    categories: ["Frontend"],
    keywords: ["solidjs", "reactive", "ui"],
    url: "https://solidjs.com",
  },
  {
    id: "spring",
    name: "Spring",
    path: "icons/spring.svg",
    categories: ["Backend"],
    keywords: ["spring", "java", "enterprise"],
    url: "https://spring.io",
  },
  {
    id: "storyblok",
    name: "Storyblok",
    path: "icons/storyblok.svg",
    categories: ["Others"],
    keywords: ["storyblok", "cms", "headless"],
    url: "https://storyblok.com",
  },
  {
    id: "storybook",
    name: "Storybook",
    path: "icons/storybook.svg",
    categories: ["Design"],
    keywords: ["storybook", "ui", "components"],
    url: "https://storybook.js.org",
  },
  {
    id: "stream",
    name: "Stream",
    path: "icons/stream.svg",
    categories: ["Others"],
    keywords: ["stream", "api", "real-time"],
    url: "https://getstream.io",
  },
  {
    id: "stylelint",
    name: "Stylelint",
    path: "icons/stylelint.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["stylelint", "css", "linting"],
    url: "https://stylelint.io",
  },
  {
    id: "sublime",
    name: "Sublime",
    path: "icons/sublime.svg",
    categories: ["Productivity"],
    keywords: ["sublime", "text editor", "code"],
    url: "https://sublimetext.com",
  },
  {
    id: "supabase",
    name: "Supabase",
    path: "icons/supabase.svg",
    categories: ["Backend", "Database"],
    keywords: ["supabase", "database", "real-time"],
    url: "https://supabase.com",
  },
  {
    id: "sveltejs",
    name: "SvelteJS",
    path: "icons/sveltejs.svg",
    categories: ["Frontend"],
    keywords: ["sveltejs", "frontend", "compiler"],
    url: "https://svelte.dev",
  },
  {
    id: "swagger",
    name: "Swagger",
    path: "icons/swagger.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["swagger", "api", "documentation"],
    url: "https://swagger.io",
  },
  {
    id: "swift",
    name: "Swift",
    path: "icons/swift.svg",
    categories: ["Languages"],
    keywords: ["swift", "programming", "apple"],
    url: "https://swift.org",
  },
  {
    id: "symfony-dark",
    name: "Symfony Dark",
    path: "icons/symfony-dark.svg",
    categories: ["Backend"],
    keywords: ["symfony", "php", "framework"],
    url: "https://symfony.com",
  },
  {
    id: "symfony-light",
    name: "Symfony Light",
    path: "icons/symfony-light.svg",
    categories: ["Backend"],
    keywords: ["symfony", "php", "framework"],
    url: "https://symfony.com",
  },
  {
    id: "tailwindcss",
    name: "Tailwind CSS",
    path: "icons/tailwindcss.svg",
    categories: ["Frontend", "Design"],
    keywords: ["tailwindcss", "utility", "css"],
    url: "https://tailwindcss.com",
  },
  {
    id: "telegram",
    name: "Telegram",
    path: "icons/telegram.svg",
    categories: ["Media"],
    keywords: ["telegram", "messaging", "secure"],
    url: "https://telegram.org",
  },
  {
    id: "tensorflow",
    name: "Tensorflow",
    path: "icons/tensorflow.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["tensorflow", "machine learning", "deep learning"],
    url: "https://www.tensorflow.org/",
  },
  {
    id: "terraform",
    name: "Terraform",
    path: "icons/terraform.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["terraform", "infrastructure", "cloud"],
    url: "https://www.terraform.io",
  },
  {
    id: "threads-dark",
    name: "Threads Dark",
    path: "icons/threads-dark.svg",
    categories: ["Media"],
    keywords: ["threads", "social", "dark mode", "meta"],
    url: "https://threads.com",
  },
  {
    id: "threads-light",
    name: "Threads Light",
    path: "icons/threads-light.svg",
    categories: ["Media"],
    keywords: ["threads", "social", "light mode", "meta"],
    url: "https://threads.com",
  },
  {
    id: "threejs-dark",
    name: "Three.js Dark",
    path: "icons/threejs-dark.svg",
    categories: ["Frontend", "Design"],
    keywords: ["threejs", "3d", "webgl"],
    url: "https://threejs.org",
  },
  {
    id: "threejs-light",
    name: "Three.js Light",
    path: "icons/threejs-light.svg",
    categories: ["Frontend", "Design"],
    keywords: ["threejs", "3d", "webgl"],
    url: "https://threejs.org",
  },
  {
    id: "tiktok",
    name: "TikTok",
    path: "icons/tiktok.svg",
    categories: ["Media"],
    keywords: ["tiktok", "video", "social"],
    url: "https://tiktok.com",
  },
  {
    id: "tinyhttp",
    name: "TinyHTTP",
    path: "icons/tinyhttp.svg",
    categories: ["Backend"],
    keywords: ["tinyhttp", "nodejs", "minimalist"],
    url: "https://tinyhttp.v1rtl.site",
  },
  {
    id: "tor",
    name: "Tor",
    path: "icons/tor.svg",
    categories: ["Browser"],
    keywords: ["tor", "privacy", "security", "browser"],
    url: "https://torproject.org",
  },
  {
    id: "tRPC",
    name: "tRPC",
    path: "icons/tRPC.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["trpc", "typescript", "rpc"],
    url: "https://trpc.io",
  },
  {
    id: "twitter",
    name: "Twitter",
    path: "icons/twitter.svg",
    categories: ["Media"],
    keywords: ["twitter", "social", "microblogging"],
    url: "https://twitter.com",
  },
  {
    id: "typescript",
    name: "TypeScript",
    path: "icons/typescript.svg",
    categories: ["Languages"],
    keywords: ["typescript", "javascript", "js", "ts", "types"],
    url: "https://typescriptlang.org",
  },
  {
    id: "ubuntu",
    name: "Ubuntu",
    path: "icons/ubuntu.svg",
    categories: ["Native App"],
    keywords: ["ubuntu", "linux", "os"],
    url: "https://ubuntu.com",
  },
  {
    id: "unjs",
    name: "Un.js",
    path: "icons/unjs.svg",
    categories: ["Frontend"],
    keywords: ["unjs", "javascript", "js", "modern"],
    url: "https://unjs.io",
  },
  {
    id: "upwork",
    name: "Upwork",
    path: "icons/upwork.svg",
    categories: ["Companies", "Media"],
    keywords: ["upwork", "freelance", "remote", "work"],
    url: "https://upwork.com",
  },
  {
    id: "upwork-basic",
    name: "Upwork Basic",
    path: "icons/upwork-basic.svg",
    categories: ["Companies", "Media"],
    keywords: ["upwork", "freelance", "remote", "work"],
    url: "https://upwork.com",
  },
  {
    id: "upwork-wordmark",
    name: "Upwork Wordmark",
    path: "icons/upwork-wordmark.svg",
    categories: ["Companies", "Media"],
    keywords: ["upwork", "freelance", "remote", "work"],
    url: "https://upwork.com",
  },
  {
    id: "vagrant",
    name: "Vagrant",
    path: "icons/vagrant.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["vagrant", "automation", "devops"],
    url: "https://www.vagrantup.com/",
  },
  {
    id: "vercel-dark",
    name: "Vercel Dark",
    path: "icons/vercel-dark.svg",
    categories: ["Backend", "DevOps & AI/ML"],
    keywords: ["vercel", "hosting", "deployment", "dark"],
    url: "https://vercel.com",
  },
  {
    id: "vercel-dark-wordmark",
    name: "Vercel Dark Wordmark",
    path: "icons/vercel-dark-wordmark.svg",
    categories: ["Backend", "DevOps & AI/ML"],
    keywords: ["vercel", "hosting", "deployment", "dark", "wordmark"],
    url: "https://vercel.com",
  },
  {
    id: "vercel-light",
    name: "Vercel Light",
    path: "icons/vercel-light.svg",
    categories: ["Backend", "DevOps & AI/ML"],
    keywords: ["vercel", "hosting", "deployment", "light"],
    url: "https://vercel.com",
  },
  {
    id: "vercel-light-wordmark",
    name: "Vercel Light Wordmark",
    path: "icons/vercel-light-wordmark.svg",
    categories: ["Backend", "DevOps & AI/ML"],
    keywords: ["vercel", "hosting", "deployment", "light", "wordmark"],
    url: "https://vercel.com",
  },
  {
    id: "vim",
    name: "Vim",
    path: "icons/vim.svg",
    categories: ["Productivity"],
    keywords: ["vim", "editor", "terminal"],
    url: "https://vim.org",
  },
  {
    id: "visualbasic",
    name: "Visual Basic",
    path: "icons/visualbasic.svg",
    categories: ["Languages"],
    keywords: ["visualbasic", "basic", "microsoft"],
    url: "https://docs.microsoft.com/en-us/dotnet/visual-basic/",
  },
  {
    id: "vscode",
    name: "Visual Studio Code",
    path: "icons/vscode.svg",
    categories: ["Productivity"],
    keywords: ["vscode", "editor", "microsoft"],
    url: "https://code.visualstudio.com",
  },
  {
    id: "vitejs",
    name: "ViteJS",
    path: "icons/vitejs.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["vitejs", "builder", "frontend"],
    url: "https://vitejs.dev",
  },
  {
    id: "vitest",
    name: "Vitest",
    path: "icons/vitest.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["vitest", "testing", "javascript", "js"],
    url: "https://vitest.dev",
  },
  {
    id: "vivaldi",
    name: "Vivaldi",
    path: "icons/vivaldi.svg",
    categories: ["Browser"],
    keywords: ["vivaldi", "web", "browser"],
    url: "https://vivaldi.com",
  },
  {
    id: "vk",
    name: "VK",
    path: "icons/vk.svg",
    categories: ["Media"],
    keywords: ["vk", "social", "network"],
    url: "https://vk.com",
  },
  {
    id: "vuejs",
    name: "Vue.js",
    path: "icons/vuejs.svg",
    categories: ["Frontend"],
    keywords: ["vuejs", "frontend", "framework"],
    url: "https://vuejs.org",
  },
  {
    id: "webassembly",
    name: "WebAssembly",
    path: "icons/webassembly.svg",
    categories: ["Others"],
    keywords: ["webassembly", "wasm", "web"],
    url: "https://webassembly.org",
  },
  {
    id: "webpack",
    name: "Webpack",
    path: "icons/webpack.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["webpack", "javascript", "js", "bundler"],
    url: "https://webpack.js.org",
  },
  {
    id: "webrtc",
    name: "WebRTC",
    path: "icons/webrtc.svg",
    categories: ["Others"],
    keywords: ["webrtc", "real-time", "communication"],
    url: "https://webrtc.org",
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    path: "icons/whatsapp.svg",
    categories: ["Media"],
    keywords: ["whatsapp", "messaging", "communication"],
    url: "https://whatsapp.com",
  },
  {
    id: "wordpress",
    name: "WordPress",
    path: "icons/wordpress.svg",
    categories: ["Others"],
    keywords: ["wordpress", "cms", "blog"],
    url: "https://wordpress.org",
  },
  {
    id: "x-dark",
    name: "X Dark",
    path: "icons/x-dark.svg",
    categories: ["Media"],
    keywords: ["x", "social", "twitter", "dark mode"],
    url: "https://x.com",
  },
  {
    id: "x-light",
    name: "X Light",
    path: "icons/x-light.svg",
    categories: ["Media"],
    keywords: ["x", "social", "twitter", "light mode"],
    url: "https://x.com",
  },
  {
    id: "xamarin",
    name: "Xamarin",
    path: "icons/xamarin.svg",
    categories: ["Native App"],
    keywords: ["xamarin", "mobile", "c#"],
    url: "https://dotnet.microsoft.com/apps/xamarin",
  },
  {
    id: "yoga",
    name: "Yoga",
    path: "icons/yoga.svg",
    categories: ["Others"],
    keywords: ["yoga", "layout", "facebook"],
    url: "https://yogalayout.com",
  },
  {
    id: "youtube",
    name: "YouTube",
    path: "icons/youtube.svg",
    categories: ["Media"],
    keywords: ["youtube", "video", "streaming"],
    url: "https://youtube.com",
  },
  {
    id: "youtube-wordmark",
    name: "YouTube Wordmark",
    path: "icons/youtube-wordmark.svg",
    categories: ["Media"],
    keywords: ["youtube", "video", "branding"],
    url: "https://youtube.com",
  },
  {
    id: "zen",
    name: "Zen",
    path: "icons/zen.svg",
    categories: ["Browser", "Productivity"],
    keywords: ["zen", "browser", "firefox", "open source"],
    url: "https://zen-browser.app/",
  },
  {
    id: "zod",
    name: "Zod",
    path: "icons/zod.svg",
    categories: ["DevOps & AI/ML"],
    keywords: ["zod", "validation", "typescript"],
    url: "https://github.com/colinhacks/zod",
  },
];

export type Category = (typeof categoriesData)[number];

export interface IconDataType {
  id: string;
  name: string;
  path: string;
  categories: Category[];
  keywords: string[];
  url: string;
}
